export type Classification = 'public' | 'official' | 'confidential' | 'restricted' | 'sealed'
export type DocType = 'fir' | 'charge-sheet' | 'witness-statement' | 'forensic-report' | 'court-order' | 'evidence-record' | 'legal-notice' | 'case-diary' | 'judgment' | 'application' | 'cctv-still' | 'expert-deposition'
export type CaseStatus = 'registered' | 'under-investigation' | 'charge-sheet-filed' | 'in-trial' | 'closed' | 'archived'
export type DocStatus = 'draft' | 'in-review' | 'approved' | 'filed' | 'rejected' | 'archived'
export type IntegrityState = 'verified' | 'pending' | 'warning' | 'failed'
export type SignatureState = 'unsigned' | 'pending' | 'valid' | 'expired' | 'revoked'
export type Role = 'investigator' | 'station-officer' | 'prosecutor' | 'court-clerk' | 'evidence-custodian' | 'auditor' | 'admin' | 'superadmin'
export type Permission = 'doc:view' | 'doc:download' | 'doc:upload' | 'doc:annotate' | 'doc:redact' | 'doc:sign' | 'doc:approve' | 'doc:share' | 'doc:delete' | 'case:view' | 'case:create' | 'case:assign' | 'access:manage' | 'audit:view' | 'audit:export' | 'retention:manage' | 'admin:users' | 'security:breakglass'
export type ControlArea = 'topbar' | 'documents' | 'cases' | 'approvals' | 'admin' | 'security'
export interface ControlDef { id: string; label: string; area: ControlArea; permission?: Permission; stub: boolean; builtin: boolean }
export interface User { id: string; name: string; designation: string; role: Role; badgeId: string; station: string; department: string; clearance: Classification; initials: string; email: string }
export interface CaseRecord { id: string; firNumber: string; title: string; crimeType: string; status: CaseStatus; classification: Classification; station: string; district: string; state: string; ioName: string; ioBadge: string; sections: string[]; cnr?: string; court?: string; registeredOn: string; updatedOn: string; description: string; parties: { role: 'complainant' | 'accused' | 'witness' | 'victim'; name: string; notes?: string }[]; tags: string[] }
export interface DocumentRecord { id: string; caseId: string; title: string; docType: DocType; classification: Classification; status: DocStatus; mimeType: string; ext: string; sizeBytes: number; pageCount: number; sha256: string; ocrState: 'not-started' | 'processing' | 'complete' | 'failed'; searchableText: string; integrity: IntegrityState; signature: { state: SignatureState; signer?: string; signedAt?: string; certId?: string }; version: number; createdBy: string; createdAt: string; updatedBy: string; updatedAt: string; custodian: string; tags: string[]; language: string; retention: { policy: string; expiresOn: string; legalHold: boolean }; summary: string }
export interface DocumentVersion { id: string; docId: string; version: number; label: string; sha256: string; authorId: string; createdAt: string; note: string }
export type AuditAction = 'login.success' | 'login.failed' | 'mfa.challenge' | 'doc.view' | 'doc.download' | 'doc.upload' | 'doc.version.create' | 'doc.share' | 'doc.sign' | 'doc.redact' | 'doc.delete' | 'doc.export' | 'access.grant' | 'access.revoke' | 'access.denied' | 'breakglass.request' | 'breakglass.grant' | 'breakglass.expire' | 'retention.hold' | 'retention.release' | 'chain.verify' | 'integrity.mismatch' | 'approval.decide'
export interface AuditEvent { id: string; ts: string; actorId: string; actorName: string; actorBadge: string; action: AuditAction; targetType: 'document' | 'case' | 'user' | 'system' | 'session'; targetId: string; targetLabel: string; caseId?: string; outcome: 'success' | 'denied' | 'failure'; severity: 'info' | 'notice' | 'warning' | 'critical'; ip: string; device: string; detail?: string; prevHash: string; hash: string }
export interface CustodyEvent { id: string; docId: string; ts: string; kind: 'intake' | 'transfer' | 'seal' | 'unseal' | 'access' | 'derivative' | 'export' | 'return'; fromCustodian?: string; toCustodian?: string; actorName: string; location: string; note: string; hash: string }
export interface ApprovalRequest { id: string; docId: string; caseId: string; kind: 'charge-sheet' | 'evidence-export' | 'redaction' | 'share-elevated' | 'bsa-certificate'; title: string; requestedBy: string; requestedAt: string; assignedTo: string; state: 'pending' | 'approved' | 'rejected' | 'changes-requested'; dueOn: string; note: string }
export interface ShareLink { id: string; docId: string; recipientId: string; recipientName: string; permission: 'view' | 'view-download'; purpose: string; createdAt: string; expiresAt: string; watermark: boolean; status: 'active' | 'expired' | 'revoked' }
export interface IntegrityReceipt { docId: string; sha256: string; merkleRoot: string; anchorTx: string; anchoredAt: string; tsaId: string; signerCert?: string; verifiedAt?: string }
export interface RolePermissionMatrix { role: Role; permissions: Permission[] }
