import { create } from 'zustand'
import { buildSeed } from '@/data/seed'
import { chainEventPayload, GENESIS, sha256Hex } from '@/lib/crypto'
import { useSession } from '@/store/session'
import type { ApprovalRequest, AuditEvent, CaseRecord, CustodyEvent, DocType, DocumentRecord, DocumentVersion, ShareLink } from '@/lib/types'
type AuditInput = Omit<AuditEvent,'id'|'ts'|'prevHash'|'hash'|'actorId'|'actorName'|'actorBadge'>
type DataState = { cases:CaseRecord[];documents:DocumentRecord[];versions:DocumentVersion[];audit:AuditEvent[];custody:CustodyEvent[];approvals:ApprovalRequest[];shares:ShareLink[];ready:boolean;getCase:(id:string)=>CaseRecord|undefined;getDocument:(id:string)=>DocumentRecord|undefined;documentsOfCase:(caseId:string)=>DocumentRecord[];versionsOf:(docId:string)=>DocumentVersion[];auditFor:(targetId:string)=>AuditEvent[];custodyFor:(docId:string)=>CustodyEvent[];addDocument:(doc:Partial<DocumentRecord>&{title:string;caseId:string;docType:DocType})=>DocumentRecord;updateDocument:(id:string,patch:Partial<DocumentRecord>)=>void;addVersion:(docId:string,label:string,note:string)=>DocumentVersion;logAudit:(event:AuditInput)=>AuditEvent;decideApproval:(id:string,state:'approved'|'rejected'|'changes-requested',note:string)=>void;grantShare:(share:Omit<ShareLink,'id'|'createdAt'|'status'>)=>void;revokeShare:(id:string)=>void;setLegalHold:(docId:string,on:boolean)=>void;verifyChain:()=>{ok:boolean;brokenAt?:string} }
const now = () => new Date().toISOString()
export const useData = create<DataState>((set,get)=>{
  let auditQueue = Promise.resolve()
  const logAudit = (event:AuditInput): AuditEvent => { const user=useSession.getState().user; const id=`AUD-LIVE-${Date.now()}`; const ts=now(); const placeholder={...event,id,ts,actorId:user.id,actorName:user.name,actorBadge:user.badgeId,prevHash:'',hash:''}; auditQueue=auditQueue.then(async()=>{const prevHash=get().audit.at(-1)?.hash??GENESIS;const base={...event,id,ts,actorId:user.id,actorName:user.name,actorBadge:user.badgeId,prevHash};const hash=await chainEventPayload(prevHash,base);set((state)=>({audit:[...state.audit,{...base,hash}]}))}); return placeholder }
  return {cases:[],documents:[],versions:[],audit:[],custody:[],approvals:[],shares:[],ready:false,
    getCase:(id)=>get().cases.find((item)=>item.id===id),getDocument:(id)=>get().documents.find((item)=>item.id===id),documentsOfCase:(caseId)=>get().documents.filter((item)=>item.caseId===caseId),versionsOf:(docId)=>get().versions.filter((item)=>item.docId===docId),auditFor:(targetId)=>get().audit.filter((item)=>item.targetId===targetId),custodyFor:(docId)=>get().custody.filter((item)=>item.docId===docId),logAudit,
    addDocument:(input)=>{const user=useSession.getState().user;const id=`DOC-LIVE-${Date.now()}`;const text=input.searchableText??'Electronic record awaiting OCR processing.';const doc:DocumentRecord={id,caseId:input.caseId,title:input.title,docType:input.docType,classification:input.classification??'official',status:input.status??'draft',mimeType:input.mimeType??'application/pdf',ext:input.ext??'pdf',sizeBytes:input.sizeBytes??0,pageCount:input.pageCount??1,sha256:input.sha256??'',ocrState:input.ocrState??'not-started',searchableText:text,integrity:input.integrity??'pending',signature:input.signature??{state:'unsigned'},version:1,createdBy:user.id,createdAt:now(),updatedBy:user.id,updatedAt:now(),custodian:input.custodian??user.id,tags:input.tags??[],language:input.language??'English',retention:input.retention??{policy:'Criminal investigation records — 10 years',expiresOn:'2036-12-31',legalHold:false},summary:input.summary??'New record awaiting review'};set((state)=>({documents:[...state.documents,doc]}));void sha256Hex(text).then((sha256)=>get().updateDocument(id,{sha256,integrity:'verified'}));logAudit({action:'doc.upload',targetType:'document',targetId:id,targetLabel:doc.title,outcome:'success',severity:'info',ip:'10.24.18.40',device:'NCRB Secure Workspace'});return doc},
    updateDocument:(id,patch)=>{set((state)=>({documents:state.documents.map((doc)=>doc.id===id?{...doc,...patch,updatedAt:now(),updatedBy:useSession.getState().user.id}:doc)}));const doc=get().getDocument(id);if(doc)logAudit({action:'doc.version.create',targetType:'document',targetId:id,targetLabel:doc.title,caseId:doc.caseId,outcome:'success',severity:'info',ip:'10.24.18.40',device:'NCRB Secure Workspace'})},
    addVersion:(docId,label,note)=>{const doc=get().getDocument(docId);if(!doc)throw new Error('Document not found');const version={id:`VER-LIVE-${Date.now()}`,docId,version:doc.version+1,label,sha256:doc.sha256,authorId:useSession.getState().user.id,createdAt:now(),note};set((state)=>({versions:[...state.versions,version],documents:state.documents.map((item)=>item.id===docId?{...item,version:version.version,updatedAt:version.createdAt}:item)}));logAudit({action:'doc.version.create',targetType:'document',targetId:docId,targetLabel:doc.title,caseId:doc.caseId,outcome:'success',severity:'info',ip:'10.24.18.40',device:'NCRB Secure Workspace'});return version},
    decideApproval:(id,state,note)=>{const item=get().approvals.find((entry)=>entry.id===id);set((data)=>({approvals:data.approvals.map((entry)=>entry.id===id?{...entry,state,note}:entry)}));if(item)logAudit({action:'approval.decide',targetType:'document',targetId:item.docId,targetLabel:item.title,caseId:item.caseId,outcome:'success',severity:'notice',ip:'10.24.18.40',device:'NCRB Secure Workspace',detail:note})},
    grantShare:(share)=>{const item={...share,id:`SHR-LIVE-${Date.now()}`,createdAt:now(),status:'active' as const};set((state)=>({shares:[...state.shares,item]}));logAudit({action:'doc.share',targetType:'document',targetId:item.docId,targetLabel:'Shared document',outcome:'success',severity:'notice',ip:'10.24.18.40',device:'NCRB Secure Workspace'})},revokeShare:(id)=>{const share=get().shares.find((item)=>item.id===id);set((state)=>({shares:state.shares.map((item)=>item.id===id?{...item,status:'revoked'}:item)}));if(share)logAudit({action:'access.revoke',targetType:'document',targetId:share.docId,targetLabel:'Share revoked',outcome:'success',severity:'notice',ip:'10.24.18.40',device:'NCRB Secure Workspace'})},
    setLegalHold:(docId,on)=>{const doc=get().getDocument(docId);set((state)=>({documents:state.documents.map((item)=>item.id===docId?{...item,retention:{...item.retention,legalHold:on}}:item)}));if(doc)logAudit({action:on?'retention.hold':'retention.release',targetType:'document',targetId:docId,targetLabel:doc.title,caseId:doc.caseId,outcome:'success',severity:'notice',ip:'10.24.18.40',device:'NCRB Secure Workspace'})},
    verifyChain:()=>{const audit=get().audit;for(let i=0;i<audit.length;i++){if(audit[i].prevHash!==(i?audit[i-1].hash:GENESIS)||!audit[i].hash)return {ok:false,brokenAt:audit[i].id}}return {ok:true}},
  }
})
void buildSeed().then((seed)=>useData.setState({...seed,ready:true}))
