import { Fragment, useEffect, useState } from 'react'
import { Check, ShieldAlert, X } from 'lucide-react'
import { toast } from 'sonner'
import { Link } from 'react-router-dom'
import { PageHeader, ClassificationBadge, WatermarkOverlay, EmptyState } from '@/components/domain'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { can, ROLE_LABELS, ROLE_MATRIX } from '@/lib/permissions'
import { useData } from '@/store/data'
import { useSession } from '@/store/session'
import type { Permission } from '@/lib/types'
import { GuardedButton, Panel } from './security-ui'

const groups:{name:string; items:[string,Permission][]}[]=[{name:'Document',items:[['View','doc:view'],['Download','doc:download'],['Upload','doc:upload'],['Share','doc:share'],['Approve','doc:approve']]},{name:'Case',items:[['View','case:view'],['Assign','case:assign']]},{name:'Audit',items:[['View log','audit:view'],['Export','audit:export']]},{name:'Administration',items:[['Manage access','access:manage'],['Retention','retention:manage'],['Break-glass','security:breakglass']]}]
type BG={doc:string;incident:string;justification:string;purpose:string;ack:boolean;until?:number}
export function AccessControlPage(){const [now]=useState(()=>Date.now());const user=useSession(s=>s.user);const users=useSession(s=>s.users);const {documents,shares,grantShare,revokeShare,logAudit}=useData();const [tab,setTab]=useState('matrix');const [share,setShare]=useState(false);const [bgOpen,setBgOpen]=useState(false);const [bg,setBg]=useState<BG>({doc:documents[0]?.id??'',incident:'INC-2026-0918',justification:'',purpose:'court direction',ack:false});const [bgRows,setBgRows]=useState<BG[]>([]);const [remaining,setRemaining]=useState(1800)
useEffect(()=>{const until=bg.until;if(!until)return;const timer=setInterval(()=>setRemaining(Math.max(0,Math.ceil((until-Date.now())/1000))),1000);return()=>clearInterval(timer)},[bg.until])
const selected=documents.find(d=>d.id===bg.doc)??documents[0];const expiry=(v:string)=>Math.max(0,Math.ceil((new Date(v).getTime()-now)/36e5));const submitShare=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const docId=String(f.get('doc'));const recipientId=String(f.get('recipient'));const doc=documents.find(d=>d.id===docId);const recipient=users.find(u=>u.id===recipientId);if(!doc||!recipient)return;grantShare({docId,recipientId,recipientName:recipient.name,permission:String(f.get('permission')) as 'view'|'view-download',purpose:String(f.get('purpose')),expiresAt:String(f.get('expires')),watermark:f.get('watermark')==='on'});toast.success('Purpose-bound share created and recorded');setShare(false)}
const breakGlass=()=>{if(bg.justification.length<20||!bg.ack){toast.error('Provide a 20 character justification and acknowledgement');return}if(!can(user,'security:breakglass')){toast.error('Emergency access requires clearance');return}const doc=documents.find(d=>d.id===bg.doc);if(!doc)return;logAudit({action:'breakglass.request',targetType:'document',targetId:doc.id,targetLabel:doc.title,caseId:doc.caseId,outcome:'success',severity:'critical',ip:'10.24.18.40',device:'NCRB Secure Workspace',detail:bg.justification});logAudit({action:'breakglass.grant',targetType:'document',targetId:doc.id,targetLabel:doc.title,caseId:doc.caseId,outcome:'success',severity:'warning',ip:'10.24.18.40',device:'NCRB Secure Workspace',detail:`${bg.purpose}; ${bg.incident}`});const row={...bg,until:Date.now()+1800000};setBg(row);setBgRows(r=>[row,...r]);setRemaining(1800);toast.success('Emergency access granted and audit teams notified')}
return <><PageHeader title="Access Control" subtitle="Purpose-bound access and recorded sharing" actions={<><span className="hidden text-sm text-muted-foreground sm:inline">{ROLE_LABELS[user.role]} · <ClassificationBadge value={user.clearance} size="sm"/></span><Button onClick={()=>{setBg({...bg,until:undefined});setBgOpen(true)}}>Break-glass request</Button></>}/><div className="mb-4 flex gap-1 border-b" role="tablist">{[['matrix','Role matrix'],['shares','Active shares'],['break','Break-glass log']].map(([id,label])=><button key={id} role="tab" aria-selected={tab===id} onClick={()=>setTab(id)} className={`border-b-2 px-3 py-2 text-sm ${tab===id?'border-primary text-primary':'border-transparent text-muted-foreground'}`}>{label}</button>)}</div>
{tab==='matrix'&&<Panel title="Role permission matrix" action={<GuardedButton perm="access:manage" onClick={()=>toast.info('Role editing is read-only in this demonstration')}>Edit matrix</GuardedButton>}><div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr className="border-b text-left"><th className="p-3">Permission</th>{ROLE_MATRIX.map(r=><th key={r.role} className={`min-w-24 p-2 text-center ${r.role===user.role?'bg-primary/10 text-primary':''}`}>{ROLE_LABELS[r.role]}</th>)}</tr></thead><tbody>{groups.map(g=><Fragment key={g.name}><tr><th colSpan={8} className="bg-muted px-3 py-2 text-left text-xs uppercase tracking-wide">{g.name}</th></tr>{g.items.map(([label,p])=><tr key={p} className="border-t"><td className="p-3">{label}</td>{ROLE_MATRIX.map(r=>{const yes=r.permissions.includes(p);return <td title={yes?'Granted':'Not granted'} key={r.role} className={`p-2 text-center ${r.role===user.role?'bg-primary/5':''}`}>{yes?<Check className="mx-auto size-4 text-success"/>:<X className="mx-auto size-4 text-muted-foreground"/>}</td>})}</tr>)}</Fragment>)}</tbody></table></div><p className="p-3 text-xs text-muted-foreground"><span className="text-success">✓</span> granted · <span>✗</span> not granted · <span className="text-warning">⚠</span> conditional access is evaluated against classification and purpose.</p></Panel>}
{tab==='shares'&&<Panel title="Active purpose-bound shares" action={<Button onClick={()=>setShare(true)}>Share document</Button>}>{shares.length===0?<EmptyState title="No active shares" description="Create a purpose-bound share for an authorised recipient."/>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs text-muted-foreground"><th className="p-3">Document</th><th>Recipient</th><th>Permission</th><th>Purpose</th><th>Expires in</th><th>Watermark</th><th>Status</th><th/></tr></thead><tbody>{shares.map(s=>{const d=documents.find(x=>x.id===s.docId);const hours=expiry(s.expiresAt);return <tr key={s.id} className="border-b"><td className="p-3"><Link className="text-primary underline" to={`/documents/${s.docId}`}>{d?.title??s.docId}</Link></td><td>{s.recipientName}</td><td>{s.permission}</td><td>{s.purpose}</td><td className={`font-mono text-xs ${hours<24?'text-destructive':''}`}>{hours}h</td><td>{s.watermark?'Yes':'No'}</td><td className="capitalize">{s.status}</td><td className="space-x-1 whitespace-nowrap"><GuardedButton perm="access:manage" onClick={()=>{revokeShare(s.id);toast.success('Share revoked and recorded')}} variant="destructive">Revoke</GuardedButton><Button size="sm" variant="ghost" onClick={()=>toast.info('Expiry extended by 24 hours for this session')}>Extend +24h</Button></td></tr>})}</tbody></table></div>}<div className="relative m-4 min-h-24 overflow-hidden rounded border bg-muted p-4"><WatermarkOverlay text={`${selected?.classification?.toUpperCase()??'OFFICIAL'} · ${user.badgeId} · ${new Date().toLocaleTimeString()}`}/><p className="relative text-xs font-semibold">Live watermark preview</p><p className="relative mt-2 text-sm">Recipient identity, badge and access time are rendered over the document preview.</p></div></Panel>}
{tab==='break'&&<Panel title="Emergency access log"><div className="p-4">{bgRows.length===0?<EmptyState icon={ShieldAlert} title="No emergency requests this session" description="Emergency access requests will be recorded in the audit chain."/>:<ul className="space-y-2">{bgRows.map((r,i)=><li key={i} className="rounded border border-warning/30 bg-warning/5 p-3 text-sm"><b>{documents.find(d=>d.id===r.doc)?.title}</b> · {r.incident} · {r.purpose} · access valid 30 minutes</li>)}</ul>}</div></Panel>}
{share&&<div className="fixed inset-0 z-50 grid place-items-center bg-background/70 p-4"><form onSubmit={submitShare} className="w-full max-w-lg space-y-4 rounded-md border bg-card p-5"><h2 className="font-semibold">Create purpose-bound share</h2><select name="doc" className="w-full rounded border bg-background p-2">{documents.map(d=><option key={d.id} value={d.id}>{d.title}</option>)}</select><select name="recipient" className="w-full rounded border bg-background p-2">{users.filter(u=>u.id!==user.id).map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select><select name="permission" className="w-full rounded border bg-background p-2"><option value="view">View only</option><option value="view-download">View and download</option></select><Textarea required name="purpose" placeholder="Purpose of access"/><Input required name="expires" type="date" max={new Date(now+30*864e5).toISOString().slice(0,10)} defaultValue={new Date(now+7*864e5).toISOString().slice(0,10)}/><label className="flex gap-2 text-sm"><input name="watermark" type="checkbox" defaultChecked/> Apply dynamic watermark</label><p className="rounded border border-warning/30 bg-warning/10 p-3 text-sm">This document is <b>{documents[0]?.classification.toUpperCase()}</b>. All access will be recorded in the audit chain.</p><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>setShare(false)}>Cancel</Button><Button type="submit">Create share</Button></div></form></div>}
{bgOpen&&!bg.until&&<div className="fixed inset-0 z-50 grid place-items-center bg-background/70 p-4"><div className="w-full max-w-lg space-y-3 rounded-md border bg-card p-5"><h2 className="font-semibold">Emergency (break-glass) access</h2><select value={bg.doc} onChange={e=>setBg({...bg,doc:e.target.value})} className="w-full rounded border bg-background p-2">{documents.map(d=><option key={d.id} value={d.id}>{d.title}</option>)}</select><Input value={bg.incident} onChange={e=>setBg({...bg,incident:e.target.value})} aria-label="Incident ID"/><Textarea value={bg.justification} onChange={e=>setBg({...bg,justification:e.target.value})} placeholder="Justification (minimum 20 characters)"/><p className="text-right text-xs text-muted-foreground">{bg.justification.length}/20 minimum</p><div className="grid grid-cols-2 gap-2 text-sm">{['medical emergency','court direction','superior order','life safety'].map(p=><label key={p}><input type="radio" checked={bg.purpose===p} onChange={()=>setBg({...bg,purpose:p})}/> {p}</label>)}</div><label className="flex gap-2 text-sm"><input type="checkbox" checked={bg.ack} onChange={e=>setBg({...bg,ack:e.target.checked})}/> Supervisor and audit team will be notified. Access valid 30 minutes.</label><div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>setBgOpen(false)}>Cancel</Button><GuardedButton perm="security:breakglass" onClick={breakGlass}>Request emergency access</GuardedButton></div></div></div>}
{bgOpen&&bg.until&&<div className="fixed inset-0 z-50 grid place-items-center bg-background/70 p-4"><div className="w-full max-w-md rounded-md border bg-card p-6 text-center"><Check className="mx-auto size-9 text-success"/><h2 className="mt-3 font-semibold">Emergency access logged</h2><p className="mt-2 text-sm text-muted-foreground">Supervisor and audit team notification is recorded in this prototype.</p><b className="mt-4 inline-block rounded bg-warning/15 px-3 py-2 font-mono text-lg">{String(Math.floor(remaining/60)).padStart(2,'0')}:{String(remaining%60).padStart(2,'0')}</b><Button className="mt-5 block w-full" onClick={()=>setBgOpen(false)}>Close</Button></div></div>}</>}
