import { useState } from 'react'
import { AlertTriangle } from 'lucide-react'
import { toast } from 'sonner'
import { PageHeader, ClassificationBadge, EmptyState } from '@/components/domain'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { useData } from '@/store/data'
import { GuardedButton, Panel } from './security-ui'
import { Control } from '@/components/rbac/Control'
const policies=[['Criminal case — 10 years','FIR, case diary','10 years','Case closure'],['Charge sheet — permanent','Charge sheet, court order','Permanent','Filing'],['Witness statement — 15 years','Witness statement','15 years','Recording']]
export function RetentionPage(){
 const {documents,setLegalHold}=useData(); const [edit,setEdit]=useState<string>(); const held=documents.filter(d=>d.retention.legalHold); const expired=documents.filter(d=>new Date(d.retention.expiresOn)<new Date()&&!d.retention.legalHold); const recommended=documents.filter(d=>!d.retention.legalHold&&['restricted','sealed'].includes(d.classification)).slice(0,4)
 const toggle=(id:string,on:boolean)=>{setLegalHold(id,on);toast.success(on?'Legal hold placed and recorded':'Legal hold released and recorded')}
  return <><PageHeader title="Retention & Legal Holds" subtitle="Purpose-bound retention controls for legal records" actions={<><Control id="retention.purge"><Button size="sm" variant="outline" onClick={()=>toast.info('Purge expired — demonstration control')}>Purge expired</Button></Control><GuardedButton perm="retention:manage" onClick={()=>toast.success('12 documents eligible for archival · 3 blocked by legal hold')}>Run retention check</GuardedButton></>}/>
 {expired.length>0&&<div className="mb-4 flex gap-2 rounded border border-warning/30 bg-warning/10 p-3 text-sm text-warning"><AlertTriangle className="size-5"/>{expired.length} documents are past their retention date without a legal hold. Review before archival.</div>}
 <Panel title="Retention policies"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="border-b text-left text-xs text-muted-foreground"><tr><th className="p-3">Policy</th><th>Applies to</th><th>Period</th><th>Trigger</th><th>Documents</th><th>Auto-purge</th><th/></tr></thead><tbody>{policies.map(p=><tr key={p[0]} className="border-b"><td className="p-3 font-medium">{p[0]}</td><td>{p[1]}</td><td>{p[2]}</td><td>{p[3]}</td><td>{Math.ceil(documents.length/3)}</td><td>Blocked by legal hold where applicable</td><td><GuardedButton perm="retention:manage" onClick={()=>setEdit(p[0])}>Edit</GuardedButton></td></tr>)}</tbody></table></div></Panel>
 <div className="mt-4 grid gap-4 xl:grid-cols-[1.5fr_1fr]"><Panel title="Legal holds"><div className="overflow-x-auto">{held.length===0?<EmptyState title="No active legal holds" description="Place a hold to prevent retention actions while review is pending."/>:<table className="w-full text-sm"><thead><tr className="border-b text-left text-xs text-muted-foreground"><th className="p-3">Case</th><th>Document</th><th>Reason</th><th>Placed on</th><th>Review date</th><th/></tr></thead><tbody>{held.map(d=><tr className="border-b" key={d.id}><td className="p-3">{d.caseId}</td><td>{d.title}</td><td>Investigation / court preservation</td><td>{d.updatedAt.slice(0,10)}</td><td>2027-03-31</td><td><GuardedButton perm="retention:manage" variant="destructive" onClick={()=>toggle(d.id,false)}>Release</GuardedButton></td></tr>)}</tbody></table>}</div></Panel><Panel title="Recommended holds"><ul className="divide-y">{recommended.map(d=><li key={d.id} className="flex items-center justify-between gap-2 p-3 text-sm"><span><b>{d.title}</b><br/><ClassificationBadge value={d.classification} size="sm"/></span><GuardedButton perm="retention:manage" onClick={()=>toggle(d.id,true)}>Place hold</GuardedButton></li>)}</ul></Panel></div>
 <section className="mt-4 rounded-md border bg-card p-4 text-sm"><h2 className="font-semibold">DPDP compliance notes</h2><ul className="mt-2 list-disc space-y-1 pl-5 text-muted-foreground"><li>Access and sharing are restricted to a recorded purpose.</li><li>An authorised legal hold overrides deletion.</li><li>Evidence exports are controlled and integrity-sealed.</li></ul><p className="mt-3 font-medium">Reference: DPDP Act, 2023. This prototype does not make automated deletion decisions.</p></section>
 {edit&&<div className="fixed inset-0 z-50 grid place-items-center bg-background/70 p-4"><form className="w-full max-w-md space-y-3 rounded border bg-card p-5" onSubmit={e=>{e.preventDefault();toast.success('Retention policy updated for this demonstration');setEdit(undefined)}}><h2 className="font-semibold">Edit retention policy</h2><Input defaultValue={edit}/><Input aria-label="Retention period" defaultValue="10 years"/><select className="w-full rounded border bg-background p-2"><option>Case closure</option><option>Filing</option></select><label className="text-sm"><input type="checkbox" defaultChecked/> Auto-purge after review</label><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>setEdit(undefined)}>Cancel</Button><Button type="submit">Save policy</Button></div></form></div>}</>}
