import { useMemo, useState } from 'react'
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { Clipboard, ExternalLink, FilePlus2, FileText, Flag, FolderOpen, Gavel, MapPin, MoreHorizontal, Printer, ShieldCheck, Share2, Upload } from 'lucide-react'
import { toast } from 'sonner'
import { Button } from '@/components/ui/button'
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from '@/components/ui/dropdown-menu'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { ClassificationBadge, EmptyState, IntegrityBadge, PageHeader, PermissionGate, RoleBadge, StatusChip, TimelineList, UserAvatar } from '@/components/domain'
import { formatBytes, formatDate, formatDateTime } from '@/lib/format'
import { denialMessage, useCan } from '@/lib/permissions'
import { Control, CustomControlsDock } from '@/components/rbac/Control'
import { useData } from '@/store/data'
import { useSession } from '@/store/session'
import type { ApprovalRequest, AuditEvent, CaseRecord, Classification, CustodyEvent, DocType, DocumentRecord, ShareLink, User } from '@/lib/types'
import { typeLabels } from '../documents/helpers'

const tabs = ['overview', 'documents', 'timeline', 'people', 'access', 'activity'] as const
type Tab = typeof tabs[number]
const tabLabel: Record<Tab, string> = { overview: 'Overview', documents: 'Documents', timeline: 'Timeline', people: 'People', access: 'Access', activity: 'Activity' }
const docTypes: DocType[] = ['fir', 'charge-sheet', 'witness-statement', 'forensic-report', 'court-order', 'evidence-record', 'legal-notice', 'case-diary', 'judgment', 'application', 'cctv-still', 'expert-deposition']
const classifications: Classification[] = ['public', 'official', 'confidential', 'restricted', 'sealed']

function Panel({ title, children, action }: { title: string; children: React.ReactNode; action?: React.ReactNode }) {
  return <section className="rounded-md border bg-card"><header className="flex items-center justify-between border-b px-4 py-3"><h2 className="text-sm font-semibold">{title}</h2>{action}</header><div className="p-4">{children}</div></section>
}

export function CaseDetailPage() {
  const { id = '' } = useParams()
  const navigate = useNavigate()
  const [params, setParams] = useSearchParams()
  const [shareOpen, setShareOpen] = useState(false)
  const [typeFilter, setTypeFilter] = useState('all')
  const [classFilter, setClassFilter] = useState('all')
  const [sort, setSort] = useState('updated')
  const [feedFilter, setFeedFilter] = useState('all')
  const can = useCan()
  const users = useSession((state) => state.users)
  const data = useData()
  const record = data.cases.find((item) => item.id === id)
  const activeTab = tabs.includes(params.get('tab') as Tab) ? params.get('tab') as Tab : 'overview'
  const setTab = (value: string) => { const next = new URLSearchParams(params); if (value === 'overview') next.delete('tab'); else next.set('tab', value); setParams(next) }

  if (!data.ready) return <EmptyState title="Loading case workspace" description="Retrieving authorised case records." />
  if (!record) return <EmptyState icon={FolderOpen} title="Case record not found" description="The requested case ID is unavailable or you no longer have access to it." action={<Button asChild variant="outline"><Link to="/cases">Back to cases</Link></Button>} />

  const documents = data.documents.filter((item) => item.caseId === record.id)
  const documentIds = new Set(documents.map((item) => item.id))
  const shares = data.shares.filter((item) => documentIds.has(item.docId))
  const audit = data.audit.filter((item) => item.caseId === record.id)
  const custody = data.custody.filter((item) => documentIds.has(item.docId))
  const approvals = data.approvals.filter((item) => item.caseId === record.id)
  const io = users.find((item) => item.badgeId === record.ioBadge)
  const copyFir = async () => { await navigator.clipboard?.writeText(record.firNumber); toast.success('FIR number copied') }
  const setHold = () => { if (!can('retention:manage')) return; const on = !documents.every((doc) => doc.retention.legalHold); documents.forEach((doc) => data.setLegalHold(doc.id, on)); toast.success(on ? 'Legal hold applied to all case records' : 'Legal hold released for all case records') }
  const exportPackage = () => { if (can('audit:export')) toast.success('BSA certificate package queued for secure export'); else toast.error(denialMessage('audit:export')) }

  return <div className="mx-auto max-w-[1600px]">
    <PageHeader title={record.title} subtitle={`${record.crimeType} · Registered ${formatDate(record.registeredOn)}`} breadcrumb={<><Link className="hover:text-primary" to="/cases">Cases</Link><span className="mx-1">/</span><span className="font-mono">{record.id}</span></>} actions={<><CustomControlsDock area="cases"/><Control id="case.transfer"><Button size="sm" variant="outline" onClick={() => toast.info('Transfer case — demonstration control')}>Transfer</Button></Control><Control id="case.close"><Button size="sm" variant="outline" onClick={() => toast.info('Close case — demonstration control')}>Close case</Button></Control><PermissionGate perm="doc:share"><Button size="sm" variant="outline" onClick={() => can('doc:share') && setShareOpen(true)}><Share2 />Share</Button></PermissionGate><PermissionGate perm="audit:export"><Button size="sm" onClick={exportPackage}><FilePlus2 />Export package</Button></PermissionGate><DropdownMenu><DropdownMenuTrigger asChild><Button aria-label="More case actions" size="icon-sm" variant="outline"><MoreHorizontal /></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={() => window.print()}><Printer />Print workspace</DropdownMenuItem><DropdownMenuItem onClick={() => toast.success('Case flagged for supervisory review')}><Flag />Flag for review</DropdownMenuItem><DropdownMenuSeparator /><PermissionGate perm="retention:manage"><DropdownMenuItem onSelect={setHold}><ShieldCheck />{documents.every((doc) => doc.retention.legalHold) ? 'Release legal hold' : 'Apply legal hold'}</DropdownMenuItem></PermissionGate></DropdownMenuContent></DropdownMenu></>} />

    <section className="mb-5 border-y bg-card px-4 py-3"><div className="flex flex-wrap items-center gap-x-4 gap-y-2"><button onClick={copyFir} aria-label="Copy FIR number" className="inline-flex items-center gap-1 font-mono text-sm font-semibold hover:text-primary">{record.firNumber}<Clipboard className="size-3.5" /></button><StatusChip status={record.status}/><ClassificationBadge value={record.classification} size="sm"/><span className="inline-flex items-center gap-1 text-xs text-muted-foreground"><MapPin className="size-3.5" />{record.station}, {record.district}, {record.state}</span></div><div className="mt-3 grid gap-3 border-t pt-3 lg:grid-cols-[1fr_auto]"><div className="flex items-center gap-3">{io ? <UserAvatar user={io} /> : <><span className="flex size-9 items-center justify-center rounded-full bg-primary text-xs font-semibold text-primary-foreground">IO</span><span className="text-sm font-medium">{record.ioName}</span></>}<span className="font-mono text-xs text-muted-foreground">{record.ioBadge}</span></div>{record.court && <div className="flex flex-wrap items-center gap-x-4 gap-y-1 text-xs"><span className="inline-flex items-center gap-1"><Gavel className="size-3.5 text-muted-foreground" />{record.court}</span>{record.cnr && <a href="https://services.ecourts.gov.in" target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 font-mono text-primary hover:underline">CNR {record.cnr}<ExternalLink className="size-3" /></a>}</div>}</div></section>

    <Tabs value={activeTab} onValueChange={setTab}><TabsList variant="line" className="w-full justify-start overflow-x-auto border-b p-0"><>{tabs.map((tab) => <TabsTrigger className="flex-none px-3" key={tab} value={tab}>{tabLabel[tab]}</TabsTrigger>)}</></TabsList>
      <TabsContent value="overview" className="mt-5"><Overview record={record} documents={documents} /></TabsContent>
      <TabsContent value="documents" className="mt-5"><Documents documents={documents} typeFilter={typeFilter} setTypeFilter={setTypeFilter} classFilter={classFilter} setClassFilter={setClassFilter} sort={sort} setSort={setSort} canUpload={can('doc:upload')} /></TabsContent>
      <TabsContent value="timeline" className="mt-5"><Timeline documents={documents} audit={audit} custody={custody} approvals={approvals} shares={shares} feedFilter={feedFilter} setFeedFilter={setFeedFilter} /></TabsContent>
      <TabsContent value="people" className="mt-5"><People record={record} users={users} /></TabsContent>
      <TabsContent value="access" className="mt-5"><Access shares={shares} documents={documents} users={users} canManage={can('access:manage')} /></TabsContent>
      <TabsContent value="activity" className="mt-5"><Activity audit={audit} custody={custody} documents={documents} /></TabsContent>
    </Tabs>
    <Dialog open={shareOpen} onOpenChange={setShareOpen}><DialogContent><DialogHeader><DialogTitle>Share case material</DialogTitle><DialogDescription>Choose individual records in Access Control. Every access is purpose-bound, watermarked and recorded.</DialogDescription></DialogHeader><div className="rounded-sm border bg-muted/40 p-3 text-sm"><p className="font-medium">{record.id}</p><p className="mt-1 text-muted-foreground">{documents.length} linked records · classification ceiling: {record.classification}</p></div><DialogFooter><DialogClose asChild><Button variant="outline">Cancel</Button></DialogClose><Button onClick={() => { setShareOpen(false); navigate('/security/access') }}>Continue to access control</Button></DialogFooter></DialogContent></Dialog>
  </div>
}

function Overview({ record, documents }: { record: CaseRecord; documents: DocumentRecord[] }) {
  const dates = [{ id: 'registered', ts: record.registeredOn, title: 'FIR registered', detail: record.firNumber, tone: 'primary' as const }, ...documents.map((doc) => ({ id: doc.id, ts: doc.createdAt, title: `${typeLabels[doc.docType]} added`, detail: doc.title, tone: 'success' as const }))]
  return <div className="grid gap-5 xl:grid-cols-[1.4fr_.9fr]"><div className="space-y-5"><Panel title="Case brief"><p className="text-sm leading-6 text-muted-foreground">{record.description}</p><div className="mt-4 flex flex-wrap gap-2">{record.sections.map((section) => <span key={section} className="rounded-sm border bg-muted px-2 py-1 font-mono text-xs">{section}</span>)}</div></Panel><Panel title="Parties"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="pb-2 font-medium">Role</th><th className="pb-2 font-medium">Name</th><th className="pb-2 font-medium">Notes</th></tr></thead><tbody>{record.parties.map((party, index) => <tr className="h-10 border-b last:border-0" key={`${party.role}-${index}`}><td className="capitalize text-muted-foreground">{party.role}</td><td className="font-medium">{party.role === 'witness' ? `Witness ${String.fromCharCode(65 + index)} (protected)` : party.name}</td><td className="text-muted-foreground">{party.role === 'witness' ? 'Identity masked in workspace' : party.notes ?? '—'}</td></tr>)}</tbody></table></div><div className="mt-3 flex flex-wrap gap-1.5">{record.tags.map((tag) => <span key={tag} className="rounded-sm bg-secondary px-2 py-1 text-xs">{tag}</span>)}</div></Panel></div><div className="space-y-5"><Panel title="Key dates"><TimelineList items={dates.sort((a, b) => b.ts.localeCompare(a.ts))} /></Panel><Panel title="Linked identifiers"><dl className="space-y-3 text-sm"><div className="flex justify-between gap-3"><dt className="text-muted-foreground">CCTNS reference</dt><dd className="font-mono">{record.firNumber}</dd></div>{record.cnr && <div className="flex justify-between gap-3"><dt className="text-muted-foreground">eCourts CNR</dt><dd className="font-mono">{record.cnr}</dd></div>}<div className="flex justify-between gap-3"><dt className="text-muted-foreground">Police station</dt><dd>{record.station}</dd></div></dl><p className="mt-4 border-t pt-3 text-xs text-muted-foreground">Identifiers are linked references — demo only. No live CCTNS, ICJS or eCourts integration is represented.</p></Panel></div></div>
}

function Documents({ documents, typeFilter, setTypeFilter, classFilter, setClassFilter, sort, setSort, canUpload }: { documents: DocumentRecord[]; typeFilter: string; setTypeFilter: (value: string) => void; classFilter: string; setClassFilter: (value: string) => void; sort: string; setSort: (value: string) => void; canUpload: boolean }) {
  const filtered = useMemo(() => documents.filter((doc) => (typeFilter === 'all' || doc.docType === typeFilter) && (classFilter === 'all' || doc.classification === classFilter)).sort((a, b) => sort === 'title' ? a.title.localeCompare(b.title) : b.updatedAt.localeCompare(a.updatedAt)), [documents, typeFilter, classFilter, sort])
  return <Panel title={`Linked records (${filtered.length})`} action={<PermissionGate perm="doc:upload"><Button size="sm" asChild><Link to={`/upload?case=${documents[0]?.caseId ?? ''}`} aria-disabled={!canUpload}><Upload />Upload</Link></Button></PermissionGate>}><div className="mb-4 flex flex-wrap gap-2"><Select value={typeFilter} onValueChange={setTypeFilter}><SelectTrigger size="sm"><SelectValue placeholder="Document type" /></SelectTrigger><SelectContent><SelectItem value="all">All types</SelectItem>{docTypes.map((type) => <SelectItem key={type} value={type}>{type.replaceAll('-', ' ')}</SelectItem>)}</SelectContent></Select><Select value={classFilter} onValueChange={setClassFilter}><SelectTrigger size="sm"><SelectValue placeholder="Classification" /></SelectTrigger><SelectContent><SelectItem value="all">All classifications</SelectItem>{classifications.map((value) => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select><Select value={sort} onValueChange={setSort}><SelectTrigger size="sm"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="updated">Recently updated</SelectItem><SelectItem value="title">Title A–Z</SelectItem></SelectContent></Select></div>{filtered.length === 0 ? <EmptyState icon={FileText} title="No matching records" description="Adjust the filters to view another linked document." /> : <div className="overflow-x-auto"><table className="w-full min-w-[950px] text-left text-xs"><thead className="border-b uppercase tracking-wide text-muted-foreground"><tr>{['Record','Classification','Status','Version','Integrity','Signature','Updated','Size'].map((head) => <th className="px-2 py-2 font-medium" key={head}>{head}</th>)}</tr></thead><tbody>{filtered.map((doc) => <tr onClick={() => window.location.assign(`/documents/${doc.id}`)} className="h-12 cursor-pointer border-b hover:bg-muted/50" key={doc.id}><td className="px-2"><span className="block font-medium text-sm">{doc.title}</span><span className="font-mono text-muted-foreground">{doc.id} · {doc.docType}</span></td><td className="px-2"><ClassificationBadge value={doc.classification} size="sm" /></td><td className="px-2"><StatusChip status={doc.status} /></td><td className="px-2 font-mono">v{doc.version}</td><td className="px-2"><IntegrityBadge state={doc.integrity} /></td><td className="px-2 capitalize">{doc.signature.state}</td><td className="px-2 mono-nums text-muted-foreground">{formatDateTime(doc.updatedAt)}</td><td className="px-2 mono-nums text-muted-foreground">{formatBytes(doc.sizeBytes)}</td></tr>)}</tbody></table></div>}</Panel>
}

function Timeline({ documents, audit, custody, approvals, shares, feedFilter, setFeedFilter }: { documents: DocumentRecord[]; audit: AuditEvent[]; custody: CustodyEvent[]; approvals: ApprovalRequest[]; shares: ShareLink[]; feedFilter: string; setFeedFilter: (value: string) => void }) {
  const items = useMemo(() => [...documents.map((doc) => ({ id: `doc-${doc.id}`, ts: doc.createdAt, title: 'Document added', detail: doc.title, group: 'docs', tone: 'success' as const })), ...custody.map((event) => ({ id: event.id, ts: event.ts, title: `Custody: ${event.kind}`, detail: `${event.location} · ${event.note}`, group: 'custody', tone: 'warning' as const })), ...approvals.map((item) => ({ id: item.id, ts: item.requestedAt, title: `Workflow: ${item.kind.replaceAll('-', ' ')}`, detail: `${item.title} · ${item.state}`, group: 'workflow', tone: 'primary' as const })), ...shares.map((share) => ({ id: share.id, ts: share.createdAt, title: 'Access grant created', detail: `${share.recipientName} · ${share.permission}`, group: 'access', tone: 'primary' as const })), ...audit.filter((item) => ['access.denied', 'doc.export', 'doc.share'].includes(item.action)).map((item) => ({ id: item.id, ts: item.ts, title: item.action.replaceAll('.', ' '), detail: item.detail ?? item.targetLabel, group: 'access', tone: item.outcome === 'denied' ? 'destructive' as const : 'primary' as const }))].filter((item) => feedFilter === 'all' || item.group === feedFilter).sort((a, b) => b.ts.localeCompare(a.ts)), [documents, audit, custody, approvals, shares, feedFilter])
  return <Panel title="Case event timeline"><div className="mb-5 flex flex-wrap gap-1.5">{['all', 'docs', 'custody', 'access', 'workflow'].map((filter) => <Button key={filter} size="xs" variant={feedFilter === filter ? 'secondary' : 'outline'} onClick={() => setFeedFilter(filter)}>{filter === 'all' ? 'All' : filter[0].toUpperCase() + filter.slice(1)}</Button>)}</div>{items.length ? <TimelineList items={items} /> : <EmptyState title="No events in this category" description="No matching case activity is recorded." />}</Panel>
}

function People({ record, users }: { record: CaseRecord; users: User[] }) { const officers = users.filter((user) => user.station === record.station || user.badgeId === record.ioBadge); return <div className="grid gap-5 lg:grid-cols-2"><Panel title="Assigned officers"><div className="space-y-3">{officers.length ? officers.map((officer) => <div className="flex items-center justify-between border-b pb-3 last:border-0 last:pb-0" key={officer.id}><UserAvatar user={officer} /><div className="text-right"><RoleBadge role={officer.role}/><p className="mt-1 font-mono text-xs text-muted-foreground">{officer.badgeId} · {officer.clearance}</p></div></div>) : <p className="text-sm text-muted-foreground">No station roster is linked to this case.</p>}</div></Panel><Panel title="Parties and protected persons"><div className="space-y-3">{record.parties.map((party, index) => <div className="flex items-start justify-between border-b pb-3 last:border-0 last:pb-0" key={`${party.role}-${index}`}><div><p className="text-sm font-medium">{party.role === 'witness' ? `Witness ${String.fromCharCode(65 + index)} (protected)` : party.name}</p><p className="mt-1 text-xs capitalize text-muted-foreground">{party.role}</p></div><span className="text-xs text-muted-foreground">{party.role === 'witness' ? 'Identity masked' : party.notes ?? 'Case party'}</span></div>)}</div></Panel></div> }

function Access({ shares, documents, users, canManage }: { shares: ShareLink[]; documents: DocumentRecord[]; users: User[]; canManage: boolean }) { return <div className="grid gap-5 xl:grid-cols-[1.4fr_.8fr]"><Panel title="Current grants" action={<PermissionGate perm="access:manage"><Button asChild size="sm" variant="outline"><Link aria-disabled={!canManage} to="/security/access">Manage access</Link></Button></PermissionGate>}>{shares.length ? <div className="space-y-3">{shares.map((share) => <div className="flex flex-wrap items-center justify-between gap-3 border-b pb-3 last:border-0 last:pb-0" key={share.id}><div><p className="text-sm font-medium">{share.recipientName} <span className="font-normal text-muted-foreground">· {share.permission}</span></p><p className="mt-1 text-xs text-muted-foreground">{documents.find((doc) => doc.id === share.docId)?.title ?? share.docId} · {share.purpose}</p></div><div className="text-right"><span className="rounded-sm border px-1.5 py-0.5 text-xs capitalize">{share.status}</span><p className="mt-1 font-mono text-xs text-muted-foreground">Expires {formatDate(share.expiresAt)}</p></div></div>)}</div> : <EmptyState title="No active case shares" description="Access grants for linked records will appear here." />}</Panel><div className="space-y-5"><Panel title="Classification policy"><p className="text-sm leading-6 text-muted-foreground">Records inherit their individual classification. Access is purpose-bound and must not exceed the case ceiling. Sealed material requires an authorised role and is always watermarked.</p></Panel><Panel title="Case members"><div className="space-y-2">{users.filter((user) => documents.some((doc) => doc.createdBy === user.id || doc.custodian === user.id)).map((user) => <div className="flex items-center justify-between" key={user.id}><span className="text-sm">{user.name}</span><RoleBadge role={user.role}/></div>)}</div></Panel></div></div> }

function Activity({ audit, custody, documents }: { audit: AuditEvent[]; custody: CustodyEvent[]; documents: DocumentRecord[] }) { return <div className="space-y-5"><Panel title="Case audit activity" action={<Button asChild variant="link" size="sm"><Link to="/security/audit">Open full audit log<ExternalLink /></Link></Button>}>{audit.length ? <div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-xs"><thead className="border-b uppercase tracking-wide text-muted-foreground"><tr><th className="py-2">Time</th><th>Actor</th><th>Action</th><th>Target</th><th>Outcome</th></tr></thead><tbody>{audit.sort((a, b) => b.ts.localeCompare(a.ts)).map((item) => <tr className="h-9 border-b" key={item.id}><td className="font-mono text-muted-foreground">{formatDateTime(item.ts)}</td><td>{item.actorName}</td><td>{item.action}</td><td>{item.targetLabel}</td><td className={item.outcome === 'denied' || item.outcome === 'failure' ? 'text-destructive' : 'text-success'}>{item.outcome}</td></tr>)}</tbody></table></div> : <EmptyState title="No case audit entries" description="Recorded case activity will appear after an authorised action." />}</Panel><Panel title="Chain of custody"><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-xs"><thead className="border-b uppercase tracking-wide text-muted-foreground"><tr><th className="py-2">Time</th><th>Record</th><th>Event</th><th>Custodian / location</th></tr></thead><tbody>{custody.map((item) => <tr className="h-9 border-b" key={item.id}><td className="font-mono text-muted-foreground">{formatDateTime(item.ts)}</td><td>{documents.find((doc) => doc.id === item.docId)?.title ?? item.docId}</td><td className="capitalize">{item.kind}</td><td>{item.actorName} · {item.location}</td></tr>)}</tbody></table></div></Panel></div> }
