import { useMemo, useState, type CSSProperties, type ReactNode } from 'react'
import { useNavigate } from 'react-router-dom'
import { Archive, Download, Grid2X2, List, Plus, Search, X } from 'lucide-react'
import { toast } from 'sonner'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Checkbox } from '@/components/ui/checkbox'
import { Tooltip, TooltipContent, TooltipTrigger } from '@/components/ui/tooltip'
import { ClassificationBadge, EmptyState, PageHeader, PermissionGate, StatusChip, UserAvatar } from '@/components/domain'
import { useData } from '@/store/data'
import { useSession } from '@/store/session'
import { formatRelative } from '@/lib/format'
import { denialMessage } from '@/lib/permissions'
import type { CaseRecord, CaseStatus, Classification } from '@/lib/types'

const statuses: CaseStatus[] = ['registered', 'under-investigation', 'charge-sheet-filed', 'in-trial', 'closed', 'archived']
const classifications: Classification[] = ['public', 'official', 'confidential', 'restricted', 'sealed']
const stripe: Record<Classification, string> = { public: 'var(--color-class-public)', official: 'var(--color-class-official)', confidential: 'var(--color-class-confidential)', restricted: 'var(--color-class-restricted)', sealed: 'var(--color-class-sealed)' }

export function CasesListPage() {
  const { cases, ready } = useData()
  const { user, users } = useSession()
  const navigate = useNavigate()
  const [query, setQuery] = useState('')
  const [status, setStatus] = useState<'all' | CaseStatus>('all')
  const [classification, setClassification] = useState<'all' | Classification>('all')
  const [station, setStation] = useState('all')
  const [sort, setSort] = useState<'updated' | 'registered'>('updated')
  const [view, setView] = useState<'table' | 'cards'>('table')
  const [selected, setSelected] = useState<string[]>([])
  const stations = useMemo(() => [...new Set(cases.map((item) => item.station))].sort(), [cases])
  const filtered = useMemo(() => cases.filter((item) => {
    const haystack = `${item.title} ${item.firNumber} ${item.parties.map((party) => party.name).join(' ')}`.toLowerCase()
    return haystack.includes(query.toLowerCase()) && (status === 'all' || item.status === status) && (classification === 'all' || item.classification === classification) && (station === 'all' || item.station === station)
  }).sort((a, b) => new Date(b[sort === 'updated' ? 'updatedOn' : 'registeredOn']).getTime() - new Date(a[sort === 'updated' ? 'updatedOn' : 'registeredOn']).getTime()), [cases, classification, query, sort, station, status])
  const clear = () => { setQuery(''); setStatus('all'); setClassification('all'); setStation('all') }
  const hasFilters = Boolean(query || status !== 'all' || classification !== 'all' || station !== 'all')
  const toggle = (id: string) => setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id])
  const selectAll = (checked: boolean) => setSelected(checked ? filtered.map((item) => item.id) : [])
  const ioUser = (item: CaseRecord) => users.find((entry) => entry.name === item.ioName) ?? { ...user, name: item.ioName, badgeId: item.ioBadge, initials: item.ioName.split(' ').map((word) => word[0]).join('').slice(0, 2) }
  const action = (label: string) => toast.info(`${label} is not available in this demonstration.`)
  const newCaseButton = <PermissionGate perm="case:create" fallback={<Tooltip><TooltipTrigger asChild><span><Button size="sm" disabled><Plus className="size-4" />New case</Button></span></TooltipTrigger><TooltipContent>{denialMessage('case:create')}</TooltipContent></Tooltip>}><Button size="sm" onClick={() => action('Case registration')}><Plus className="size-4" />New case</Button></PermissionGate>

  if (!ready) return <><PageHeader title="Cases" subtitle="Loading investigation records…" /><div className="h-72 animate-pulse rounded-md border bg-muted" /></>
  return <div className="space-y-5">
    <PageHeader title="Cases" subtitle="Investigation records registered with this workspace." breadcrumb="Operations / Cases" actions={newCaseButton} />
    <section className="rounded-md border bg-card p-3"><div className="grid gap-2 lg:grid-cols-[minmax(220px,1fr)_repeat(4,minmax(130px,.42fr))_auto]"><label className="relative"><span className="sr-only">Search cases</span><Search className="pointer-events-none absolute left-2.5 top-2.5 size-4 text-muted-foreground"/><Input value={query} onChange={(event) => setQuery(event.target.value)} className="pl-9" placeholder="Search FIR, case title or party" /></label><FilterSelect label="Status" value={status} onChange={(value) => setStatus(value as 'all' | CaseStatus)} options={statuses}/><FilterSelect label="Classification" value={classification} onChange={(value) => setClassification(value as 'all' | Classification)} options={classifications}/><FilterSelect label="Station" value={station} onChange={setStation} options={stations}/><FilterSelect label="Sort" value={sort} onChange={(value) => setSort(value as 'updated' | 'registered')} options={['updated', 'registered']}/><div className="flex rounded-md border p-0.5"><button aria-label="Table view" onClick={() => setView('table')} className={`rounded-sm p-1.5 ${view === 'table' ? 'bg-accent text-accent-foreground' : 'text-muted-foreground'}`}><List className="size-4" /></button><button aria-label="Card view" onClick={() => setView('cards')} className={`rounded-sm p-1.5 ${view === 'cards' ? 'bg-accent text-accent-foreground' : 'text-muted-foreground'}`}><Grid2X2 className="size-4" /></button></div></div><div className="mt-3 flex items-center justify-between gap-3"><p className="text-xs text-muted-foreground"><span className="mono-nums font-medium text-foreground">{filtered.length}</span> of <span className="mono-nums">{cases.length}</span> cases</p>{hasFilters && <Button variant="ghost" size="sm" onClick={clear}><X className="size-3.5" />Clear filters</Button>}</div></section>
    {!filtered.length ? <EmptyState icon={Search} title="No matching cases" description="Try another FIR number, party name, station or classification." action={hasFilters ? <Button variant="outline" onClick={clear}>Clear filters</Button> : undefined} /> : view === 'table' ? <div className="overflow-auto rounded-md border bg-card"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="sticky top-0 z-10 bg-muted text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="w-10 px-3 py-3"><Checkbox aria-label="Select all visible cases" checked={filtered.length > 0 && filtered.every((item) => selected.includes(item.id))} onCheckedChange={(checked) => selectAll(checked === true)} /></th><th className="px-3 py-3">FIR / case</th><th className="px-3 py-3">Status</th><th className="px-3 py-3">Classification</th><th className="px-3 py-3">Station / district</th><th className="px-3 py-3">Investigating officer</th><th className="px-3 py-3">Sections</th><th className="px-3 py-3">Updated</th></tr></thead><tbody>{filtered.map((item) => <CaseRow key={item.id} item={item} selected={selected.includes(item.id)} onToggle={() => toggle(item.id)} onOpen={() => navigate(`/cases/${item.id}`)} officer={ioUser(item)} />)}</tbody></table></div> : <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{filtered.map((item) => <article key={item.id} className="class-stripe rounded-md border bg-card p-4" style={{ '--stripe-color': stripe[item.classification] } as CSSProperties}><div className="flex items-start justify-between gap-3"><button onClick={() => navigate(`/cases/${item.id}`)} className="min-w-0 text-left"><p className="mono-nums text-xs text-primary">{item.firNumber}</p><h2 className="mt-1 line-clamp-2 text-sm font-semibold">{item.title}</h2><p className="mt-1 text-xs text-muted-foreground">{item.crimeType}</p></button><Checkbox aria-label={`Select ${item.firNumber}`} checked={selected.includes(item.id)} onCheckedChange={() => toggle(item.id)} /></div><div className="mt-3 flex flex-wrap gap-2"><StatusChip status={item.status}/><ClassificationBadge value={item.classification} size="sm"/></div><div className="mt-3 border-t pt-3 text-xs text-muted-foreground"><p>{item.station} · {item.district}</p><p className="mt-1">IO: {item.ioName} · updated {formatRelative(item.updatedOn)}</p></div><Button variant="outline" size="sm" className="mt-3 w-full" onClick={() => navigate(`/cases/${item.id}`)}>Open case</Button></article>)}</div>}
     {selected.length > 0 && <div className="sticky bottom-3 z-20 flex flex-wrap items-center justify-between gap-3 rounded-md border border-primary/30 bg-card px-4 py-3 shadow-lg"><p className="text-sm"><span className="mono-nums font-semibold">{selected.length}</span> case{selected.length === 1 ? '' : 's'} selected</p><div className="flex gap-2"><PermissionGate perm="audit:export" fallback={<DeniedAction label={denialMessage('audit:export')} icon={<Download className="size-4"/>}>Export</DeniedAction>}><Button variant="outline" size="sm" onClick={() => action('Secure export')}><Download className="size-4"/>Export</Button></PermissionGate><PermissionGate perm="case:assign" fallback={<DeniedAction label={denialMessage('case:assign')} icon={<Archive className="size-4"/>}>Archive</DeniedAction>}><Button variant="outline" size="sm" onClick={() => action('Case archive')}><Archive className="size-4"/>Archive</Button></PermissionGate><Button variant="ghost" size="sm" onClick={() => setSelected([])}>Clear</Button></div></div>}
  </div>
}

function FilterSelect({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[] }) { return <label><span className="sr-only">{label}</span><select aria-label={label} value={value} onChange={(event) => onChange(event.target.value)} className="h-9 w-full rounded-md border bg-background px-2 text-sm capitalize outline-none focus:ring-2 focus:ring-ring"><option value="all">All {label.toLowerCase()}s</option>{options.map((option) => <option key={option} value={option}>{option.replaceAll('-', ' ')}</option>)}</select></label> }
function DeniedAction({ label, icon, children }: { label: string; icon: ReactNode; children: string }) { return <Tooltip><TooltipTrigger asChild><span><Button variant="outline" size="sm" disabled>{icon}{children}</Button></span></TooltipTrigger><TooltipContent>{label}</TooltipContent></Tooltip> }
function CaseRow({ item, selected, onToggle, onOpen, officer }: { item: CaseRecord; selected: boolean; onToggle: () => void; onOpen: () => void; officer: ReturnType<typeof useSession.getState>['user'] }) { return <tr className="h-10 border-t hover:bg-muted/60"><td className="px-3"><Checkbox aria-label={`Select ${item.firNumber}`} checked={selected} onCheckedChange={onToggle}/></td><td className="px-3 py-2"><button onClick={onOpen} className="block max-w-64 text-left focus-visible:underline"><span className="mono-nums block text-xs text-primary">{item.firNumber}</span><span className="block truncate font-medium">{item.title}</span><span className="block text-xs text-muted-foreground">{item.crimeType}</span></button></td><td className="px-3"><StatusChip status={item.status}/></td><td className="px-3"><ClassificationBadge value={item.classification} size="sm"/></td><td className="px-3 text-xs"><span className="block max-w-36 truncate">{item.station}</span><span className="text-muted-foreground">{item.district}</span></td><td className="px-3"><UserAvatar user={officer} size="sm"/></td><td className="mono-nums px-3 text-xs">{item.sections.slice(0, 2).join(' · ')}{item.sections.length > 2 && <span className="text-muted-foreground"> +{item.sections.length - 2}</span>}</td><td className="px-3 text-xs text-muted-foreground">{formatRelative(item.updatedOn)}</td></tr> }
