import type { ReactNode } from 'react'
import { useState } from 'react'
import { CheckCircle2, Clipboard, FileText, FolderOpen, LockKeyhole, ShieldAlert, ShieldCheck, ShieldQuestion, Users } from 'lucide-react'
import { toast } from 'sonner'
import { cn } from 'cn'
import { denialMessage, ROLE_LABELS, useCan } from '@/lib/permissions'
import { shortHash } from '@/lib/crypto'
import { formatDateTime } from '@/lib/format'
import type { ApprovalRequest, CaseStatus, Classification, DocStatus, DocumentRecord, IntegrityState, Permission, Role, User } from '@/lib/types'
export function PageHeader({title,subtitle,breadcrumb,actions}:{title:string;subtitle?:string;breadcrumb?:ReactNode;actions?:ReactNode}){return <header className="mb-6 flex flex-wrap items-end justify-between gap-4"><div>{breadcrumb&&<div className="mb-1 text-xs text-muted-foreground">{breadcrumb}</div>}<h1 className="text-xl font-semibold tracking-tight">{title}</h1>{subtitle&&<p className="mt-1 text-sm text-muted-foreground">{subtitle}</p>}</div>{actions&&<div className="flex items-center gap-2">{actions}</div>}</header>}
const classStyles:Record<Classification,string>={public:'border-class-public/30 bg-class-public/10 text-class-public',official:'border-class-official/30 bg-class-official/10 text-class-official',confidential:'border-class-confidential/30 bg-class-confidential/10 text-class-confidential',restricted:'border-class-restricted/30 bg-class-restricted/10 text-class-restricted',sealed:'border-class-sealed/30 bg-class-sealed/10 text-class-sealed'}
export function ClassificationBadge({value,size='default'}:{value:Classification;size?:'sm'|'default'}){return <span className={cn('inline-flex items-center gap-1 rounded-sm border font-medium uppercase tracking-wide',classStyles[value],size==='sm'?'px-1.5 py-0.5 text-[10px]':'px-2 py-1 text-xs')}><LockKeyhole className="size-3"/>{value}</span>}
export function IntegrityBadge({state,onClick}:{state:IntegrityState;onClick?:()=>void}){const config={verified:[ShieldCheck,'SHA-256 verified','text-success bg-success/10 border-success/30'],pending:[ShieldQuestion,'Awaiting anchor','text-muted-foreground bg-muted border-border'],warning:[ShieldAlert,'Metadata warning','text-warning bg-warning/10 border-warning/30'],failed:[ShieldAlert,'Integrity failed','text-destructive bg-destructive/10 border-destructive/30']} as const;const [Icon,label,style]=config[state];return <button type="button" onClick={onClick} className={cn('inline-flex items-center gap-1 rounded-sm border px-2 py-1 text-xs font-medium',style)}><Icon className="size-3.5"/>{label}</button>}
export function StatusChip({status}:{status:CaseStatus|DocStatus|ApprovalRequest['state']}){return <span className={cn('rounded-sm border px-2 py-1 text-xs font-medium capitalize',status==='approved'||status==='filed'||status==='closed'?'border-success/30 bg-success/10 text-success':status==='rejected'?'border-destructive/30 bg-destructive/10 text-destructive':'border-warning/30 bg-warning/10 text-warning')}>{status.replaceAll('-',' ')}</span>}
export function RoleBadge({role}:{role:Role}){return <span className="rounded-sm bg-secondary px-2 py-1 text-xs text-secondary-foreground">{ROLE_LABELS[role]}</span>}
export function UserAvatar({user,size='default'}:{user:User;size?:'sm'|'default'|'lg'}){const sizes={sm:'size-7 text-[10px]',default:'size-9 text-xs',lg:'size-11 text-sm'};return <span className="inline-flex items-center gap-2"><span className={cn('inline-flex shrink-0 items-center justify-center rounded-full bg-primary font-semibold text-primary-foreground',sizes[size])}>{user.initials}</span><span className="min-w-0"><span className="block truncate text-sm font-medium">{user.name}</span><span className="block truncate text-xs text-muted-foreground">{user.designation}</span></span></span>}
export function HashText({value,copyable=true}:{value:string;copyable?:boolean}){const [copied,setCopied]=useState(false);const copy=async()=>{await navigator.clipboard?.writeText(value);setCopied(true);toast.success('Hash copied');setTimeout(()=>setCopied(false),1200)};return <span className="inline-flex items-center gap-1 font-mono text-xs text-muted-foreground" title={value}>{shortHash(value)}{copyable&&<button aria-label="Copy hash" onClick={copy} className="rounded p-0.5 hover:bg-accent">{copied?<CheckCircle2 className="size-3 text-success"/>:<Clipboard className="size-3"/>}</button>}</span>}
export function PermissionGate({perm,children,fallback}:{perm:Permission;children:ReactNode;fallback?:ReactNode}){const allowed=useCan()(perm);if(allowed)return <>{children}</>;if(fallback!==undefined)return <>{fallback}</>;return <span title={denialMessage(perm)} aria-disabled="true" className="inline-block cursor-not-allowed opacity-50">{children}</span>}
export function EmptyState({icon:Icon=FolderOpen,title,description,action}:{icon?:typeof FolderOpen;title:string;description:string;action?:ReactNode}){return <section className="flex min-h-56 flex-col items-center justify-center rounded-md border border-dashed bg-card px-6 text-center"><Icon className="mb-3 size-8 text-muted-foreground"/><h2 className="text-sm font-semibold">{title}</h2><p className="mt-1 max-w-md text-sm text-muted-foreground">{description}</p>{action&&<div className="mt-4">{action}</div>}</section>}
export function StatCard({label,value,delta,icon:Icon=FileText,tone='primary'}:{label:string;value:string|number;delta?:string;icon?:typeof FileText;tone?:'primary'|'success'|'warning'|'destructive'}){const tones={primary:'text-primary',success:'text-success',warning:'text-warning',destructive:'text-destructive'};return <section className="class-stripe rounded-md border bg-card p-4"><div className="flex justify-between"><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">{label}</p><Icon className={cn('size-4',tones[tone])}/></div><p className="mt-2 text-2xl font-semibold">{value}</p>{delta&&<p className="mt-1 text-xs text-muted-foreground">{delta}</p>}</section>}
export function TimelineList({items}:{items:{id:string;ts:string;title:string;detail?:string;tone?:'primary'|'success'|'warning'|'destructive'}[]}){return <ol className="space-y-0">{items.map((item)=><li key={item.id} className="relative border-l pl-5 pb-5 last:pb-0"><span className={cn('absolute -left-1.5 top-1 size-3 rounded-full border-2 border-card bg-primary',item.tone==='success'&&'bg-success',item.tone==='warning'&&'bg-warning',item.tone==='destructive'&&'bg-destructive')}/><p className="text-sm font-medium">{item.title}</p>{item.detail&&<p className="text-sm text-muted-foreground">{item.detail}</p>}<time className="mt-1 block font-mono text-xs text-muted-foreground">{formatDateTime(item.ts)}</time></li>)}</ol>}
export function WatermarkOverlay({text}:{text:string}){return <div aria-hidden className="pointer-events-none absolute inset-0 z-10 flex rotate-[-32deg] flex-wrap content-center justify-around gap-x-14 gap-y-16 overflow-hidden opacity-10"><span className="text-xl font-bold">{text}</span><span className="text-xl font-bold">{text}</span><span className="text-xl font-bold">{text}</span></div>}
export function DocumentFacsimile({doc,watermark}:{doc:DocumentRecord;watermark?:string}){const fir=doc.docType==='fir';return <article className="relative mx-auto min-h-[620px] max-w-[760px] overflow-hidden bg-card p-8 font-serif text-[13px] leading-6 text-foreground shadow-sm sm:p-12"><header className="border-b-2 border-foreground pb-4 text-center"><div className="mx-auto mb-1 flex size-11 items-center justify-center rounded-full border-2 border-gold text-gold">✦</div><p className="text-xs uppercase tracking-[.18em]">Government of Maharashtra · Police Department</p><h2 className="mt-1 text-lg font-bold">{fir?'FIRST INFORMATION REPORT':doc.title.toUpperCase()}</h2><p className="text-xs">Electronic Record · {doc.id} · {doc.caseId}</p></header><div className="mt-6 whitespace-pre-wrap">{doc.searchableText}</div><footer className="mt-8 border-t pt-4 text-right text-sm"><p>Digitally maintained secure record</p><p>SHA-256: {shortHash(doc.sha256)}</p></footer>{watermark&&<WatermarkOverlay text={watermark}/>}</article>}
export const DomainIcons={Users}
