import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { CheckCircle2, FileCheck2, FileDown, KeyRound, Search, ShieldCheck, XCircle } from 'lucide-react'
import { toast } from 'sonner'
import { PageHeader, ClassificationBadge, EmptyState, HashText, StatCard, StatusChip, TimelineList, UserAvatar } from '@/components/domain'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { can } from '@/lib/permissions'
import { formatDateTime, formatRelative } from '@/lib/format'
import { shortHash } from '@/lib/crypto'
import { useData } from '@/store/data'
import { useSession } from '@/store/session'
import type { ApprovalRequest } from '@/lib/types'

type Tab = 'pending' | 'approved' | 'rejected' | 'all'
const kindLabel: Record<ApprovalRequest['kind'], string> = { 'charge-sheet':'Charge sheet', 'evidence-export':'Evidence export', redaction:'Redaction', 'share-elevated':'Elevated share', 'bsa-certificate':'BSA certificate' }
const now = new Date('2026-09-28T12:00:00+05:30').getTime()
const ageHours = (iso: string) => Math.max(1, Math.round((now - new Date(iso).getTime()) / 36e5))

export function ApprovalsPage() {
  const { approvals, documents, custody, decideApproval, updateDocument, logAudit } = useData()
  const { user, users } = useSession()
  const [tab, setTab] = useState<Tab>('pending'), [kind, setKind] = useState('all'), [assignee, setAssignee] = useState('all'), [query, setQuery] = useState('')
  const [selected, setSelected] = useState<ApprovalRequest | null>(null), [decision, setDecision] = useState<'reject'|'changes'|null>(null), [note, setNote] = useState('')
  const [ceremony, setCeremony] = useState(false), [pin, setPin] = useState(''), [signing, setSigning] = useState(false), [cert, setCert] = useState(false), [exportOpen, setExportOpen] = useState(false)
  const rows = useMemo(() => approvals.filter(a => (tab === 'all' || (tab === 'rejected' ? a.state === 'rejected' : a.state === tab)) && (kind === 'all' || a.kind === kind) && (assignee === 'all' || a.assignedTo === assignee) && `${a.title} ${a.id}`.toLowerCase().includes(query.toLowerCase())), [approvals, tab, kind, assignee, query])
  const mine = approvals.filter(a => a.state === 'pending' && a.assignedTo === user.id).length
  const pending = approvals.filter(a => a.state === 'pending').length
  const in7 = (state: ApprovalRequest['state']) => approvals.filter(a => a.state === state).length
  const selectedDoc = documents.find(d => d.id === selected?.docId)
  const finish = (state: 'approved'|'rejected'|'changes-requested', message: string) => { if (!selected) return; decideApproval(selected.id, state, note || 'Decision recorded after workflow review.'); toast.success(message); setSelected(null); setDecision(null); setNote('') }
  const sign = () => { if (!selectedDoc || pin !== '123456') { toast.error('Enter the demonstration PIN 123456'); return } setSigning(true); window.setTimeout(() => { setSigning(false); setCert(true) }, 950) }
  const confirmSign = () => { if (!selected || !selectedDoc) return; const certId = `CCA-DEMO-2026-${selected.id.slice(-3)}`; updateDocument(selectedDoc.id, { signature:{ state:'valid', signer:user.name, signedAt:'2026-09-28T12:00:00+05:30', certId } }); logAudit({ action:'doc.sign', targetType:'document', targetId:selectedDoc.id, targetLabel:selectedDoc.title, caseId:selectedDoc.caseId, outcome:'success', severity:'notice', ip:'10.24.18.40', device:'NCRB Secure Workspace', detail:`CCA eSign certificate ${certId}` }); decideApproval(selected.id, 'approved', 'Approved with CCA demonstration eSign.'); toast.success('Approval recorded and signature certificate issued'); setCert(false); setCeremony(false); setSelected(null) }
  return <>
    <PageHeader title="Approvals" subtitle="Review workflow decisions and electronically sign authorised records." breadcrumb="Workflow / Approvals" />
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><StatCard label="Pending — mine" value={mine} tone="warning" /><StatCard label="Pending — all" value={pending} tone="warning" /><StatCard label="Approved · 7d" value={in7('approved')} tone="success" /><StatCard label="Rejected · 7d" value={in7('rejected')} tone="destructive" /><StatCard label="Avg. decision time" value="18h 24m" tone="primary" /></div>
    <section className="mt-5 rounded-md border bg-card"><div className="flex flex-wrap items-center gap-2 border-b p-3"><select aria-label="Filter by request kind" value={kind} onChange={e=>setKind(e.target.value)} className="h-9 rounded-sm border bg-background px-2 text-sm"><option value="all">All request kinds</option>{Object.entries(kindLabel).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select aria-label="Filter by assignee" value={assignee} onChange={e=>setAssignee(e.target.value)} className="h-9 rounded-sm border bg-background px-2 text-sm"><option value="all">All assignees</option>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select><label className="relative ml-auto"><Search className="absolute left-2 top-2.5 size-4 text-muted-foreground"/><Input aria-label="Search approvals" value={query} onChange={e=>setQuery(e.target.value)} className="h-9 w-56 pl-8" placeholder="Search queue" /></label></div>
      <div className="flex items-center gap-1 border-b px-3">{(['pending','approved','rejected','all'] as Tab[]).map(value=><button key={value} onClick={()=>setTab(value)} className={`border-b-2 px-3 py-2 text-sm font-medium capitalize ${tab===value?'border-primary text-primary':'border-transparent text-muted-foreground'}`}>{value} {value==='all'?approvals.length:approvals.filter(a=>value==='rejected'?a.state==='rejected':a.state===value).length}</button>)}</div>
      {rows.length === 0 ? <EmptyState icon={FileCheck2} title={`No ${tab} requests`} description="No workflow requests match the selected filters." /> : <div className="overflow-x-auto"><table className="w-full min-w-[930px] text-left text-sm"><thead className="bg-muted/50 text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="p-3">Due</th><th>Request</th><th>Requested by</th><th>Assigned to</th><th>Age</th><th>State</th><th /></tr></thead><tbody>{rows.map(a=>{const requester=users.find(u=>u.id===a.requestedBy)!; const assigned=users.find(u=>u.id===a.assignedTo)!; const overdue=new Date(a.dueOn).getTime()-now<48*36e5; return <tr key={a.id} className="h-14 border-t hover:bg-muted/30"><td className={`p-3 font-mono text-xs ${overdue&&a.state==='pending'?'text-destructive':'text-muted-foreground'}`}>{overdue&&a.state==='pending'?'Due <48h':'Due'}<br/>{formatRelative(a.dueOn)}</td><td><span className="mr-2 rounded-sm border bg-secondary px-1.5 py-0.5 text-[10px] font-medium uppercase">{kindLabel[a.kind]}</span><p className="mt-1 font-medium">{a.title}</p><Link className="text-xs text-primary hover:underline" to={`/cases/${a.caseId}`}>{a.caseId}</Link></td><td><UserAvatar user={requester} size="sm" /></td><td><UserAvatar user={assigned} size="sm" /></td><td className="font-mono text-xs">{ageHours(a.requestedAt)}h</td><td><StatusChip status={a.state}/></td><td className="p-3 text-right"><Button size="sm" variant="outline" onClick={()=>setSelected(a)}>Review</Button></td></tr>})}</tbody></table></div>}</section>
    <Dialog open={!!selected} onOpenChange={open=>!open&&setSelected(null)}><DialogContent className="max-h-[92vh] max-w-2xl overflow-y-auto"><DialogHeader><DialogTitle>Workflow review</DialogTitle><DialogDescription>{selected?.id} · Due {selected && formatDateTime(selected.dueOn)}</DialogDescription></DialogHeader>{selected && selectedDoc && <div className="space-y-5"><div className="rounded-sm border-l-4 border-primary bg-primary/5 p-3"><ClassificationBadge value={selectedDoc.classification} size="sm"/><Link to={`/documents/${selectedDoc.id}`} className="ml-3 text-sm font-medium text-primary hover:underline">{selectedDoc.title}</Link><p className="mt-2 text-sm text-muted-foreground">{selected.note}</p></div><Workflow state={selected.state}/><div className="grid gap-4 md:grid-cols-2"><div><h3 className="mb-2 text-sm font-semibold">Request timeline</h3><TimelineList items={[{id:'request',ts:selected.requestedAt,title:'Request submitted',detail:`Assigned to ${users.find(u=>u.id===selected.assignedTo)?.name}`,tone:'primary'},{id:'review',ts:selected.dueOn,title:'Decision due',detail:'Workflow SLA deadline',tone:'warning'}]}/></div><div className="rounded-sm border p-3 text-sm"><p className="font-semibold">Record integrity</p><p className="mt-2 text-muted-foreground">SHA-256 document hash</p><HashText value={selectedDoc.sha256}/><p className="mt-3 text-muted-foreground">Signature: {selectedDoc.signature.state}</p></div></div>{selected.kind==='bsa-certificate'&&<BsaPreview request={selected} docHash={selectedDoc.sha256} custodyCount={custody.filter(c=>c.docId===selectedDoc.id).length} officer={user.name} onExport={()=>setExportOpen(true)}/>}<DecisionActions allowed={can(user,'doc:approve')} state={selected.state} onApprove={()=> (selected.kind==='charge-sheet'||selected.kind==='bsa-certificate') ? setCeremony(true) : finish('approved','Approval recorded')} onReject={()=>setDecision('reject')} onChanges={()=>setDecision('changes')} /></div>}</DialogContent></Dialog>
    <Dialog open={decision!==null} onOpenChange={open=>!open&&setDecision(null)}><DialogContent><DialogHeader><DialogTitle>{decision==='reject'?'Reject request':'Request changes'}</DialogTitle><DialogDescription>A recorded reason is required for the workflow audit trail.</DialogDescription></DialogHeader><Textarea aria-label="Decision note" value={note} onChange={e=>setNote(e.target.value)} placeholder="State the review reason or required correction…"/><DialogFooter><Button variant="outline" onClick={()=>setDecision(null)}>Cancel</Button><Button disabled={!note.trim()} variant={decision==='reject'?'destructive':'default'} onClick={()=>finish(decision==='reject'?'rejected':'changes-requested',decision==='reject'?'Request rejected':'Changes requested')}>Record decision</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={ceremony} onOpenChange={setCeremony}><DialogContent><DialogHeader><DialogTitle>CCA eSign ceremony</DialogTitle><DialogDescription>The signature covers the document hash, not the document content.</DialogDescription></DialogHeader>{!can(user,'doc:sign')?<div className="rounded-sm border border-destructive/30 bg-destructive/10 p-4 text-sm"><XCircle className="mb-2 size-5 text-destructive"/>Signing blocked: your current role does not hold <code>doc:sign</code> permission.</div>: cert?<div className="space-y-3 text-center"><div className="mx-auto flex size-16 items-center justify-center rounded-full border-4 border-gold text-gold"><ShieldCheck className="size-8"/></div><p className="font-semibold">Certificate issued</p><p className="text-sm text-muted-foreground">Signer: {user.name} · CCA-DEMO-2026-{selected?.id.slice(-3)}</p><p className="font-mono text-xs">TSA 2026-09-28 12:00 IST · SHA-256</p><Button onClick={confirmSign}>Confirm approval</Button></div>:<div className="space-y-4"><div className="rounded-sm bg-muted p-3 text-sm"><p className="font-medium">Identity verified</p><p className="text-muted-foreground">{user.name} · {user.badgeId} · {user.designation}</p></div><div><label className="text-sm font-medium">6-digit signing PIN <span className="font-normal text-muted-foreground">(demo: 123456)</span></label><Input aria-label="Six digit signing PIN" className="mt-1 font-mono tracking-[0.35em]" maxLength={6} inputMode="numeric" value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,''))}/></div><div className="rounded-sm border p-3"><p className="text-xs text-muted-foreground">Document SHA-256</p><p className="mt-1 font-mono text-xs">{selectedDoc && shortHash(selectedDoc.sha256,12)}</p>{signing&&<p className="mt-2 text-xs text-primary">Hashing and applying signature…</p>}</div><Button className="w-full" onClick={sign} disabled={signing}><KeyRound className="mr-2 size-4"/>Sign document hash</Button></div>}</DialogContent></Dialog>
    <Dialog open={exportOpen} onOpenChange={setExportOpen}><DialogContent><DialogHeader><DialogTitle>Export BSA certificate package</DialogTitle><DialogDescription>Exports the certificate, document hash and custody summary. Access is logged.</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={()=>setExportOpen(false)}>Cancel</Button><Button disabled={!can(user,'doc:download')} title={!can(user,'doc:download')?'Requires document download permission':undefined} onClick={()=>{toast.success('BSA certificate package receipt created');setExportOpen(false)}}><FileDown className="mr-2 size-4"/>Export PDF</Button></DialogFooter></DialogContent></Dialog>
  </>
}
function Workflow({state}:{state:ApprovalRequest['state']}) { const step=state==='approved'?2:state==='pending'?1:0; return <ol className="flex items-start justify-between gap-1">{['Intake','Review','Approved','Filed','Archived'].map((label,i)=><li key={label} className="flex flex-1 items-center gap-1"><span className={`flex size-6 shrink-0 items-center justify-center rounded-full border text-xs ${i<=step?'border-primary bg-primary text-primary-foreground':'text-muted-foreground'}`}>{i<step?<CheckCircle2 className="size-3"/>:i+1}</span><span className={`hidden text-xs sm:inline ${i===step?'font-semibold':'text-muted-foreground'}`}>{label}</span>{i<4&&<span className="h-px flex-1 bg-border"/>}</li>)}</ol> }
function DecisionActions({allowed,state,onApprove,onReject,onChanges}:{allowed:boolean;state:ApprovalRequest['state'];onApprove:()=>void;onReject:()=>void;onChanges:()=>void}) { if(state!=='pending') return <div className="rounded-sm bg-muted p-3 text-sm text-muted-foreground">This request has already been decided.</div>; return <div className="flex flex-wrap gap-2 border-t pt-4"><Button disabled={!allowed} title={!allowed?'Requires Station Officer clearance':undefined} onClick={onApprove}><CheckCircle2 className="mr-2 size-4"/>Approve</Button><Button disabled={!allowed} title={!allowed?'Requires Station Officer clearance':undefined} variant="outline" onClick={onChanges}>Request changes</Button><Button disabled={!allowed} title={!allowed?'Requires Station Officer clearance':undefined} variant="destructive" onClick={onReject}>Reject</Button></div> }
function BsaPreview({request,docHash,custodyCount,officer,onExport}:{request:ApprovalRequest;docHash:string;custodyCount:number;officer:string;onExport:()=>void}) { return <section className="border bg-card p-5 font-serif text-sm leading-6"><div className="flex justify-between border-b-2 border-foreground pb-3"><div><p className="text-xs uppercase tracking-widest">Bharatiya Sakshya Adhiniyam, 2023</p><h3 className="text-lg font-semibold">Certificate for Electronic Record</h3></div><FileCheck2 className="size-8 text-gold"/></div><dl className="mt-4 grid gap-x-5 gap-y-2 sm:grid-cols-2"><div><dt className="text-muted-foreground">Case</dt><dd>{request.caseId}</dd></div><div><dt className="text-muted-foreground">Record</dt><dd>{request.docId}</dd></div><div className="sm:col-span-2"><dt className="text-muted-foreground">SHA-256 hash</dt><dd className="font-mono text-xs">{docHash}</dd></div><div><dt className="text-muted-foreground">Custody summary</dt><dd>{custodyCount} recorded events; original preserved.</dd></div><div><dt className="text-muted-foreground">Device particulars</dt><dd>Secure evidence workstation · OCR verified.</dd></div></dl><p className="mt-5 border-t pt-3">Certified by: {officer}<br/>Signature block: pending authorised eSign</p><Button size="sm" variant="outline" className="mt-3 font-sans" onClick={onExport}><FileDown className="mr-2 size-4"/>Export PDF</Button></section> }
