import { useEffect, useRef, useState } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { CheckCircle2, ChevronLeft, ChevronRight, Clipboard, FileText, ShieldCheck, UploadCloud, X } from 'lucide-react'
import { toast } from 'sonner'
import { PageHeader, ClassificationBadge, PermissionGate } from '@/components/domain'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { useData } from '@/store/data'
import { useSession } from '@/store/session'
import { sha256Hex } from '@/lib/crypto'
import { formatBytes, formatDateTime } from '@/lib/format'
import type { Classification, DocType } from '@/lib/types'

const steps = ['Select file', 'OCR & classify', 'Metadata', 'Security & custody', 'Review & submit']
const demoText = `FIRST INFORMATION REPORT\nPolice Station Cyber, Mumbai\nFIR/PS-CYBER/2026/0451\nStatement records an unauthorised UPI transfer of INR 48,500. The complainant received a fraudulent customer-care call and shared an OTP. Preliminary enquiry identifies beneficiary account trail and mobile device identifiers. Offences under BNS section 318(4) and IT Act section 66D are invoked. This electronic record is prepared for investigation and secure case filing.`
const docTypes: DocType[] = ['fir','charge-sheet','witness-statement','forensic-report','court-order','evidence-record','legal-notice','case-diary','judgment','application','cctv-still','expert-deposition']
const classifications: { value: Classification; label: string }[] = [{value:'official',label:'Routine investigation record'},{value:'confidential',label:'Case-sensitive access'},{value:'restricted',label:'Need-to-know evidence'},{value:'sealed',label:'Court / protected record'}]

export default function UploadWizardPage() {
  const [params, setParams] = useSearchParams(); const navigate = useNavigate()
  const cases = useData(s=>s.cases); const addDocument = useData(s=>s.addDocument); const user = useSession(s=>s.user)
  const initialStep = Math.max(1, Math.min(5, Number(params.get('step')) || 1)); const [step,setStep]=useState(initialStep)
  const [caseId,setCaseId]=useState(params.get('case') || ''); const [file,setFile]=useState<File | null>(null); const [hash,setHash]=useState(''); const [hashProgress,setHashProgress]=useState(0); const [hashing,setHashing]=useState(false)
  const [ocr,setOcr]=useState(0); const [ocrDone,setOcrDone]=useState(false); const [title,setTitle]=useState(''); const [docType,setDocType]=useState<DocType>('evidence-record'); const [classification,setClassification]=useState<Classification>('official'); const [tags,setTags]=useState<string[]>([]); const [tag,setTag]=useState(''); const [language,setLanguage]=useState('English'); const [retention,setRetention]=useState('Criminal investigation records — 10 years'); const [hold,setHold]=useState(false); const [custody,setCustody]=useState(false); const [watermark,setWatermark]=useState(true); const [errors,setErrors]=useState<Record<string,string>>({}); const [submitted,setSubmitted]=useState<{id:string;sha:string}|null>(null)
  const input = useRef<HTMLInputElement>(null)
  useEffect(()=>{ setParams(prev=>{const n=new URLSearchParams(prev); n.set('step',String(step)); if(caseId)n.set('case',caseId); return n},{replace:true}) },[step,caseId,setParams])
  useEffect(()=>{ if(step!==2 || ocrDone) return; let p=0; const timer=window.setInterval(()=>{p+=4;setOcr(p);if(p>=100){window.clearInterval(timer);setOcrDone(true)}},100); return ()=>window.clearInterval(timer) },[step,ocrDone])
  const processFile=async(selected:File)=>{setFile(selected);setHashing(true);setHashProgress(12);setTitle(selected.name.replace(/\.[^.]+$/,'')); const tick=window.setInterval(()=>setHashProgress(p=>Math.min(92,p+8)),110); try {const result=await sha256Hex(await selected.arrayBuffer());setHash(result);setHashProgress(100);toast.success('SHA-256 intake hash computed')} finally {window.clearInterval(tick);setHashing(false)} }
  const demo=async()=>{const f=new File([demoText],'cyber-fraud-intake-memo.txt',{type:'text/plain'});await processFile(f);setDocType('evidence-record');setTitle('Cyber fraud intake memorandum')}
  const validate=()=>{const next:Record<string,string>={};if(step===1){if(!file)next.file='Select a file or use the demo document.';if(!caseId)next.case='Select the linked case.';if(!hash)next.file='Hash calculation must complete before continuing.'}if(step===3){if(!effectiveTitle.trim())next.title='Title is required.';if(!docType)next.type='Document type is required.'}if(step===4&&!custody)next.custody='Confirm the custody details to continue.';setErrors(next);return !Object.keys(next).length}
  const next=()=>{if(!validate())return;setStep(s=>Math.min(5,s+1))}; const submit=()=>{if(!validate())return;const doc=addDocument({title:effectiveTitle,caseId,docType,classification,tags,language,sha256:hash,searchableText:demoText,pageCount:Math.max(1,Math.ceil(demoText.length/900)),sizeBytes:file?.size??0,mimeType:file?.type||'text/plain',ext:file?.name.split('.').pop()||'txt',ocrState:'complete',integrity:'verified',retention:{policy:retention,expiresOn:'2036-12-31',legalHold:hold},summary:`Intake record for ${cases.find(c=>c.id===caseId)?.firNumber ?? 'linked case'}.`});setSubmitted({id:doc.id,sha:hash});toast.success('Document submitted to vault')}
  if(submitted)return <main><PageHeader title="Document received" subtitle="The original was registered as an immutable intake record."/><section className="max-w-2xl rounded-md border bg-card p-8 text-center"><CheckCircle2 className="mx-auto size-14 text-success"/><h2 className="mt-4 text-xl font-semibold">SHA-256 verified at intake</h2><p className="mt-2 text-sm text-muted-foreground">Document ID <span className="font-mono">{submitted.id}</span> · custody intake audit has been recorded.</p><p className="mt-5 break-all rounded bg-muted p-3 font-mono text-xs">{submitted.sha}</p><div className="mt-6 flex justify-center gap-3"><Button onClick={()=>navigate(`/documents/${submitted.id}`)}>Open document</Button><Button variant="outline" onClick={()=>{setSubmitted(null);setStep(1);setFile(null);setHash('');setOcrDone(false);setCaseId('');setTags([])}}>Upload another</Button></div></section></main>
  const currentCase=cases.find(c=>c.id===caseId)
  const effectiveTitle=title||(currentCase?`${currentCase.crimeType} — supporting electronic record`:'')
  return <main><PageHeader title="Secure intake" subtitle="Register an original, compute its SHA-256 hash, and establish custody." actions={<Button variant="ghost" onClick={()=>{if(window.confirm('Cancel this intake? Unsaved details will be discarded.'))navigate('/documents')}}><X className="mr-1 size-4"/>Cancel</Button>}/><ol className="mb-7 grid grid-cols-5 gap-1" aria-label="Upload steps">{steps.map((label,i)=><li key={label} className="min-w-0"><div className={`h-1 ${i+1<=step?'bg-primary':'bg-border'}`}/><span className={`mt-2 block text-xs ${i+1===step?'font-semibold text-primary':'text-muted-foreground'}`}>{i+1}. <span className="hidden lg:inline">{label}</span></span></li>)}</ol>
  <section className="max-w-4xl rounded-md border bg-card p-5 sm:p-7">
  {step===1&&<div className="space-y-5"><h2 className="font-semibold">Select original and linked case</h2><div onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const f=e.dataTransfer.files[0];if(f)void processFile(f)}} className="rounded-md border-2 border-dashed p-8 text-center"><UploadCloud className="mx-auto size-8 text-primary"/><p className="mt-2 text-sm font-medium">Drop PDF, image or DOCX here</p><p className="text-xs text-muted-foreground">The file remains in this browser demo; only its hash is registered.</p><input ref={input} className="hidden" type="file" accept=".pdf,.jpg,.jpeg,.png,.docx" onChange={e=>{const f=e.target.files?.[0];if(f)void processFile(f)}}/><div className="mt-4 flex justify-center gap-2"><Button variant="outline" onClick={()=>input.current?.click()}>Choose file</Button><Button variant="secondary" onClick={()=>void demo()}>Use demo document</Button></div></div>{errors.file&&<p className="text-sm text-destructive">{errors.file}</p>}{file&&<div className="flex items-center gap-3 rounded border p-3"><FileText className="size-7 text-primary"/><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{file.name}</p><p className="text-xs text-muted-foreground">{formatBytes(file.size)} · {file.type || 'unknown type'}</p></div><span className="text-xs font-medium">{hashing?`Hashing ${hashProgress}%`:'Hash ready'}</span></div>}<label className="block text-sm font-medium">Linked case<select value={caseId} onChange={e=>setCaseId(e.target.value)} className="mt-1 h-10 w-full rounded border bg-background px-3"><option value="">Select case</option>{cases.map(c=><option key={c.id} value={c.id}>{c.id} — {c.title}</option>)}</select></label>{errors.case&&<p className="text-sm text-destructive">{errors.case}</p>}</div>}
  {step===2&&<div className="space-y-5"><h2 className="font-semibold">OCR & classification</h2>{!ocrDone?<div className="space-y-3">{['Ingesting original','Page segmentation','Text extraction','Language detection','Search indexing'].map((x,i)=><div key={x}><div className="mb-1 flex justify-between text-sm"><span>{x}</span><span className="text-muted-foreground">{Math.max(0,Math.min(100,ocr-i*20))}%</span></div><div className="h-2 overflow-hidden rounded bg-muted"><div className="h-full bg-primary transition-all" style={{width:`${Math.max(0,Math.min(100,ocr-i*20))}%`}}/></div></div>)}</div>:<><div className="grid gap-3 sm:grid-cols-3"><label className="text-sm">Detected type<select value={docType} onChange={e=>setDocType(e.target.value as DocType)} className="mt-1 h-9 w-full rounded border bg-background px-2">{docTypes.map(x=><option key={x}>{x}</option>)}</select></label><p className="text-sm">Language<strong className="mt-1 block">English</strong></p><p className="text-sm">Confidence<strong className="mt-1 block text-success">96.4%</strong></p></div><pre className="max-h-44 overflow-auto rounded border bg-muted p-3 font-mono text-xs whitespace-pre-wrap">{demoText.slice(0,300)}…</pre><Button variant="outline" onClick={()=>{setOcr(0);setOcrDone(false)}}>Re-run OCR</Button></>}</div>}
  {step===3&&<div className="space-y-5"><h2 className="font-semibold">Describe and protect the record</h2><label className="block text-sm font-medium">Document title<Input value={effectiveTitle} onChange={e=>setTitle(e.target.value)} className="mt-1"/></label>{errors.title&&<p className="text-sm text-destructive">{errors.title}</p>}<div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Document type<select value={docType} onChange={e=>setDocType(e.target.value as DocType)} className="mt-1 h-10 w-full rounded border bg-background px-3">{docTypes.map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm font-medium">Station<Input value={currentCase?.station||'Select case first'} readOnly className="mt-1 bg-muted"/></label></div><fieldset><legend className="mb-2 text-sm font-medium">Classification</legend><div className="grid gap-2 sm:grid-cols-2">{classifications.map(item=><label key={item.value} className={`flex cursor-pointer gap-2 rounded border p-3 ${classification===item.value?'border-primary bg-primary/5':''}`}><input type="radio" checked={classification===item.value} onChange={()=>setClassification(item.value)}/><span><ClassificationBadge value={item.value} size="sm"/><span className="mt-1 block text-xs text-muted-foreground">{item.label}</span></span></label>)}</div></fieldset><label className="block text-sm font-medium">Tags<div className="mt-1 flex flex-wrap gap-1 rounded border p-2">{tags.map(x=><button key={x} onClick={()=>setTags(t=>t.filter(v=>v!==x))} className="rounded bg-secondary px-2 py-1 text-xs">{x} ×</button>)}<input value={tag} onChange={e=>setTag(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&tag.trim()){e.preventDefault();setTags(t=>[...t,tag.trim()]);setTag('')}}} placeholder="Type and press Enter" className="min-w-32 flex-1 bg-transparent text-sm outline-none"/></div></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Language<select value={language} onChange={e=>setLanguage(e.target.value)} className="mt-1 h-10 w-full rounded border bg-background px-3"><option>English</option><option>Hindi</option><option>Marathi</option></select></label><label className="text-sm font-medium">Retention policy<select value={retention} onChange={e=>setRetention(e.target.value)} className="mt-1 h-10 w-full rounded border bg-background px-3"><option>Criminal investigation records — 10 years</option><option>Permanent court record</option><option>Evidence retention — case closure + 7 years</option></select></label></div><PermissionGate perm="retention:manage" fallback={<p className="text-xs text-muted-foreground">Legal hold requires Station Officer clearance.</p>}><label className="flex gap-2 text-sm"><input type="checkbox" checked={hold} onChange={e=>setHold(e.target.checked)}/>Place this document on legal hold</label></PermissionGate></div>}
  {step===4&&<div className="space-y-5"><h2 className="font-semibold">Security & custody receipt</h2><div className="rounded border bg-muted/40 p-4"><div className="flex items-center gap-2"><ShieldCheck className="size-5 text-success"/><strong>Intake integrity receipt</strong></div><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><div className="sm:col-span-2"><dt className="text-muted-foreground">SHA-256 · Web Crypto</dt><dd className="mt-1 flex gap-2 break-all font-mono text-xs">{hash}<button aria-label="Copy full SHA-256 hash" onClick={()=>{void navigator.clipboard.writeText(hash);toast.success('Hash copied')}}><Clipboard className="size-4"/></button></dd></div><div><dt className="text-muted-foreground">Computed at</dt><dd>{formatDateTime(new Date().toISOString())}</dd></div><div><dt className="text-muted-foreground">Custodian</dt><dd>{user.name} · {user.badgeId}</dd></div><div><dt className="text-muted-foreground">Merkle batch</dt><dd className="font-mono text-xs">Pending next daily anchor</dd></div><div><dt className="text-muted-foreground">Access class</dt><dd><ClassificationBadge value={classification} size="sm"/></dd></div></dl></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={watermark} onChange={e=>setWatermark(e.target.checked)}/>Apply viewer watermark for shared access</label><label className="flex gap-2 rounded border p-3 text-sm"><input type="checkbox" checked={custody} onChange={e=>setCustody(e.target.checked)}/>I confirm chain-of-custody intake details are accurate</label>{errors.custody&&<p className="text-sm text-destructive">{errors.custody}</p>}</div>}
  {step===5&&<div className="space-y-5"><h2 className="font-semibold">Review before vault submission</h2><div className="grid gap-3 text-sm sm:grid-cols-2"><p><span className="text-muted-foreground">Original</span><br/>{file?.name}</p><p><span className="text-muted-foreground">Case</span><br/>{currentCase?.firNumber}</p><p><span className="text-muted-foreground">Metadata</span><br/>{effectiveTitle} · {docType}</p><p><span className="text-muted-foreground">Protection</span><br/><ClassificationBadge value={classification} size="sm"/> · {retention}</p><p className="sm:col-span-2"><span className="text-muted-foreground">SHA-256</span><br/><span className="break-all font-mono text-xs">{hash}</span></p></div></div>}
  <footer className="mt-8 flex justify-between border-t pt-5"><Button variant="outline" disabled={step===1} onClick={()=>setStep(s=>s-1)}><ChevronLeft className="mr-1 size-4"/>Back</Button>{step===5?<Button onClick={submit}>Submit to vault<CheckCircle2 className="ml-1 size-4"/></Button>:<Button onClick={next}>Continue<ChevronRight className="ml-1 size-4"/></Button>}</footer></section></main>
}
