import { Fragment, useMemo, useState } from 'react'
import { Check, CircleAlert, Database, Link2, Shield, UsersRound, X } from 'lucide-react'
import { toast } from 'sonner'
import { ClassificationBadge, EmptyState, PageHeader, RoleBadge, UserAvatar } from '@/components/domain'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { can, ROLE_LABELS, ROLE_MATRIX } from '@/lib/permissions'
import { formatDateTime } from '@/lib/format'
import { useData } from '@/store/data'
import { useSession } from '@/store/session'
import type { Permission, Role, User } from '@/lib/types'

type Tab = 'users'|'roles'|'stations'|'status'|'integrations'
const permissions: Array<[string, Permission[]]> = [
  ['Document', ['doc:view','doc:download','doc:upload','doc:annotate','doc:redact','doc:sign','doc:approve','doc:share','doc:delete']],
  ['Case', ['case:view','case:create','case:assign']], ['Access & audit', ['access:manage','audit:view','audit:export','retention:manage','security:breakglass']], ['Administration', ['admin:users']],
]
const permissionName: Record<Permission,string> = {'doc:view':'View records','doc:download':'Download records','doc:upload':'Upload records','doc:annotate':'Annotate records','doc:redact':'Redact records','doc:sign':'eSign document','doc:approve':'Approve workflow','doc:share':'Share records','doc:delete':'Delete records','case:view':'View cases','case:create':'Create cases','case:assign':'Assign cases','access:manage':'Manage access','audit:view':'View audit','audit:export':'Export audit','retention:manage':'Manage retention','admin:users':'Manage users','security:breakglass':'Break-glass access'}
const roles = ROLE_MATRIX.map(m=>m.role)

export function AdminPage() {
  const { user, users } = useSession(); const data = useData(); const [tab,setTab] = useState<Tab>('users'); const [selected,setSelected] = useState<User|null>(null); const [invite,setInvite] = useState(false)
  if (!can(user,'admin:users')) return <><PageHeader title="Administration" subtitle="System configuration and authorised user access." breadcrumb="System / Administration"/><EmptyState icon={Shield} title="Restricted" description="Requires System Administrator clearance. Switch to the System Administrator demo role to view this workspace."/></>
  return <><PageHeader title="Administration" subtitle="System configuration, authorisation and service assurance." breadcrumb="System / Administration" actions={<Button onClick={()=>setInvite(true)}><UsersRound className="mr-2 size-4"/>Invite user</Button>}/><div className="mb-5 flex overflow-x-auto border-b">{([['users','Users'],['roles','Roles & permissions'],['stations','Departments & stations'],['status','System status'],['integrations','Integrations']] as [Tab,string][]).map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`shrink-0 border-b-2 px-3 py-2 text-sm font-medium ${tab===id?'border-primary text-primary':'border-transparent text-muted-foreground'}`}>{label}</button>)}</div>
    {tab==='users'&&<UsersTab users={users} audit={data.audit} onSelect={setSelected}/>} {tab==='roles'&&<RolesTab currentRole={user.role}/>} {tab==='stations'&&<StationsTab users={users} cases={data.cases} documents={data.documents}/>} {tab==='status'&&<StatusTab audit={data.audit} documents={data.documents} verify={data.verifyChain}/>} {tab==='integrations'&&<Integrations/>}
    <UserDialog user={selected} audit={data.audit} onOpenChange={open=>!open&&setSelected(null)}/><Dialog open={invite} onOpenChange={setInvite}><DialogContent><DialogHeader><DialogTitle>Invite authorised user</DialogTitle><DialogDescription>This demonstration does not send email or create an account.</DialogDescription></DialogHeader><Input aria-label="Official email address" placeholder="officer@agency.gov.in"/><DialogFooter><Button variant="outline" onClick={()=>setInvite(false)}>Cancel</Button><Button onClick={()=>{toast.success('Invitation workflow queued — demonstration only');setInvite(false)}}>Queue invitation</Button></DialogFooter></DialogContent></Dialog>
  </>
}
function UsersTab({users,audit,onSelect}:{users:User[];audit:ReturnType<typeof useData.getState>['audit'];onSelect:(u:User)=>void}) { return <section className="overflow-x-auto rounded-md border bg-card"><table className="w-full min-w-[1000px] text-left text-sm"><thead className="bg-muted/50 text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="p-3">Officer</th><th>Role</th><th>Badge</th><th>Station</th><th>Clearance</th><th>Status</th><th>Last login</th></tr></thead><tbody>{users.map((u,i)=><tr key={u.id} onClick={()=>onSelect(u)} className="h-14 cursor-pointer border-t hover:bg-muted/30"><td className="p-3"><UserAvatar user={u} size="sm"/></td><td><RoleBadge role={u.role}/></td><td className="font-mono text-xs">{u.badgeId}</td><td>{u.station}</td><td><ClassificationBadge value={u.clearance} size="sm"/></td><td><span className="text-success">Active · MFA on</span></td><td className="font-mono text-xs">{formatDateTime(audit.find(a=>a.actorId===u.id)?.ts ?? `2026-09-${String(20-i).padStart(2,'0')}T09:00:00+05:30`)}</td></tr>)}</tbody></table></section> }
function UserDialog({user,audit,onOpenChange}:{user:User|null;audit:ReturnType<typeof useData.getState>['audit'];onOpenChange:(open:boolean)=>void}) { const allowed=user?ROLE_MATRIX.find(m=>m.role===user.role)?.permissions ?? []:[]; return <Dialog open={!!user} onOpenChange={onOpenChange}><DialogContent className="max-h-[85vh] overflow-y-auto"><DialogHeader><DialogTitle>{user?.name}</DialogTitle><DialogDescription>{user?.designation} · {user?.badgeId}</DialogDescription></DialogHeader>{user&&<><div className="rounded-sm border p-3 text-sm"><p>{user.station}</p><p className="mt-1 text-muted-foreground">{user.email}</p></div><section><h3 className="mb-2 text-sm font-semibold">Role-derived permissions</h3><div className="flex flex-wrap gap-1">{allowed.map(p=><span key={p} className="rounded-sm bg-secondary px-2 py-1 text-xs">{permissionName[p]}</span>)}</div></section><section><h3 className="mb-2 text-sm font-semibold">Recent audit activity</h3><div className="space-y-2">{audit.filter(a=>a.actorId===user.id).slice(0,4).map(a=><div key={a.id} className="border-l-2 border-primary pl-3 text-sm"><p>{a.action.replaceAll('.',' ')}</p><p className="font-mono text-xs text-muted-foreground">{formatDateTime(a.ts)} · {a.targetLabel}</p></div>)}</div></section></>}</DialogContent></Dialog> }
function RolesTab({currentRole}:{currentRole:Role}) { return <section className="rounded-md border bg-card"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-3 text-xs text-muted-foreground"><span>Legend: <b className="text-success">✓ Granted</b> · <b className="text-warning">⚠ Conditional</b> · <b>✗ Not granted</b></span><Button size="sm" variant="outline" disabled title="Read-only in demo">Edit matrix</Button></div><div className="overflow-x-auto"><table className="w-full min-w-[950px] text-center text-xs"><thead><tr className="border-b"><th className="p-3 text-left">Permission</th>{roles.map(role=><th key={role} className={`p-2 ${role===currentRole?'bg-primary/10 text-primary':''}`}>{ROLE_LABELS[role]}</th>)}</tr></thead><tbody>{permissions.map(([group,perms])=><Fragment key={group}><tr><th colSpan={8} className="bg-muted/60 px-3 py-2 text-left text-xs uppercase tracking-wide text-muted-foreground">{group}</th></tr>{perms.map(p=><tr key={p} className="border-t"><td className="p-2 text-left">{permissionName[p]}</td>{roles.map(role=>{const yes=ROLE_MATRIX.find(m=>m.role===role)?.permissions.includes(p); const conditional=!yes && (p==='doc:sign'||p==='doc:approve'||p==='audit:export'); return <td key={role} title={`${ROLE_LABELS[role]}: ${yes?'Granted':conditional?'Conditional approval path':'Not granted'}`} className={role===currentRole?'bg-primary/5':''}>{yes?<Check className="mx-auto size-4 text-success"/>:conditional?<CircleAlert className="mx-auto size-4 text-warning"/>:<X className="mx-auto size-4 text-muted-foreground"/>}</td>})}</tr>)}</Fragment>)}</tbody></table></div></section> }
function StationsTab({users,cases,documents}:{users:User[];cases:ReturnType<typeof useData.getState>['cases'];documents:ReturnType<typeof useData.getState>['documents']}) { const entries=useMemo(()=>Array.from(new Set([...cases.map(c=>c.station),...users.map(u=>u.station)])).map((station,i)=>({station,code:`MH-${String(i+1).padStart(3,'0')}`,district:cases.find(c=>c.station===station)?.district ?? 'Mumbai',cases:cases.filter(c=>c.station===station).length,docs:documents.filter(d=>cases.find(c=>c.id===d.caseId)?.station===station).length,officers:users.filter(u=>u.station===station).length})),[cases,documents,users]); return <section className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{entries.map(e=><article key={e.station} className="rounded-md border bg-card p-4"><div className="flex items-start justify-between"><div><h2 className="font-semibold">{e.station}</h2><p className="mt-1 font-mono text-xs text-muted-foreground">{e.code} · {e.district}</p></div><UsersRound className="size-5 text-primary"/></div><dl className="mt-4 grid grid-cols-3 gap-2 text-center text-sm"><div><dt className="text-muted-foreground">Active cases</dt><dd className="mt-1 font-semibold">{e.cases}</dd></div><div><dt className="text-muted-foreground">Documents</dt><dd className="mt-1 font-semibold">{e.docs}</dd></div><div><dt className="text-muted-foreground">Officers</dt><dd className="mt-1 font-semibold">{e.officers}</dd></div></dl></article>)}</section> }
function StatusTab({audit,documents,verify}:{audit:ReturnType<typeof useData.getState>['audit'];documents:ReturnType<typeof useData.getState>['documents'];verify:ReturnType<typeof useData.getState>['verifyChain']}) { const services=[['Vault storage','Operational','42 ms','99.99%'],['OCR engine','Operational','186 ms','99.95%'],['Anchor node','Degraded','842 ms','99.72%'],['eSign gateway','Operational','218 ms','99.98%'],['Backup','Operational','64 ms','100%']]; const classifications=['official','confidential','restricted','sealed'] as const; return <div className="space-y-5"><section className="grid gap-3 md:grid-cols-2 xl:grid-cols-5">{services.map(([name,state,latency,uptime])=><article key={name} className="rounded-md border bg-card p-3"><p className="text-sm font-semibold">{name}</p><p className={`mt-2 text-xs ${state==='Operational'?'text-success':'text-warning'}`}>{state}</p><p className="mt-2 font-mono text-xs text-muted-foreground">{latency} · {uptime}</p></article>)}</section><section className="grid gap-5 lg:grid-cols-[1fr_1.2fr]"><article className="rounded-md border bg-card p-4"><h2 className="font-semibold">Storage by classification</h2><div className="mt-4 space-y-3">{classifications.map(c=>{const n=documents.filter(d=>d.classification===c).length;return <div key={c}><div className="flex justify-between text-xs"><span className="capitalize">{c}</span><span>{n} records</span></div><div className="mt-1 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full bg-primary" style={{width:`${Math.max(8,n/documents.length*100)}%`}}/></div></div>})}</div></article><article className="rounded-md border bg-card p-4"><div className="flex items-center justify-between"><h2 className="font-semibold">Audit chain</h2><Button size="sm" onClick={()=>{const result=verify(); if(result.ok){toast.success(`Chain intact · ${audit.length} events verified`)}else{toast.error(`Critical: chain broken at ${result.brokenAt}`)}}}><Shield className="mr-2 size-4"/>Run chain verification</Button></div><div className="mt-3 space-y-2">{audit.filter(a=>a.action==='chain.verify'||a.targetType==='system').slice(-6).reverse().map(a=><div key={a.id} className="border-l-2 border-primary pl-3 text-sm"><p>{a.action.replaceAll('.',' ')} · {a.outcome}</p><p className="font-mono text-xs text-muted-foreground">{formatDateTime(a.ts)}</p></div>)}</div></article></section></div> }
function Integrations(){const rows=[['CCTNS','FIR/PS-CYBER/2026/0451','Police case reference'],['ICJS','ICJS-MH-PN-2026-0184','Interoperability reference'],['eCourts','MHPUN01-000184-2026','CNR / eFiling reference']];return <><section className="grid gap-4 md:grid-cols-3">{rows.map(([name,id,detail])=><article key={name} className="rounded-md border bg-card p-4"><Link2 className="size-5 text-primary"/><h2 className="mt-3 font-semibold">{name}</h2><span className="mt-2 inline-block rounded-sm bg-success/10 px-2 py-1 text-xs text-success">Linked (demo)</span><p className="mt-3 font-mono text-xs">{id}</p><p className="mt-1 text-sm text-muted-foreground">{detail}</p></article>)}</section><p className="mt-4 flex items-center gap-2 text-sm text-muted-foreground"><Database className="size-4"/>Demonstration only — no live integration.</p></>}
